### ISSUE TITLE
Incorrect docs regarding reusing Redis connection?

### ISSUE THREAD

**Issue by combustpizza** [taskforcesh/bullmq#108]
Based on docs here: https://docs.bullmq.io/guide/connections

It says to pass `IORedis` instance as the `connection` option to both worker and queue, however when I do that, I get the following error from the worker:

```
TypeError: client.moveToActive is not a function
    at Function.moveToActive (/home/project/node_modules/bullmq/dist/classes/scripts.js:247:37)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Worker.moveToActive (/home/project/node_modules/bullmq/dist/classes/worker.js:135:31)
```

And the queue throws this when `add` is called:

```
TypeError: client.addJob is not a function
    at Function.addJob (/home/project/node_modules/bullmq/dist/classes/scripts.js:38:23)
    at Job.addJob (/home/project/node_modules/bullmq/dist/classes/job.js:323:34)
    at Function.create (/home/project/node_modules/bullmq/dist/classes/job.js:32:28)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Queue.add (/home/project/node_modules/bullmq/dist/classes/queue.js:34:25)
```

Interestingly enough, if I pass the `IORedis` instance as the `client` option, then it works just fine. So am I missing something or the documentation is not correct.outdated?

**BullMQ version:** 1.6.6

**Comment by rhinodavid** [comment]
Seeing this too.
<img width="850" alt="Screen Shot 2020-01-27 at 9 21 38 PM" src="https://user-images.githubusercontent.com/5778036/73235284-04606400-414b-11ea-897c-1dac656879ad.png">

**Comment by peadrakw** [comment]
`bplist00Ô
X$versionY$archiverT$topX$objects�† _NSKeyedArchiverÑ    Troot€¢
U$null_bhttps://dev.azure.com/nextjs/963cd205-0f00-47a0-82e1-9484fd0cb6c3/_apis/build/builds/10695/logs/38$)27ILQSV\�������������
���������������Á
`

**Comment by rhinodavid** [comment]
So from the quickstart guide:
```
import { Worker } from 'bullmq'

const worker = new Worker(queueName, async job => {
    // Will print { foo: 'bar'} for the first job
    // and { qux: 'baz' } for the second.
    console.log(job.data);
});
```

The second argument is the processing function. The options are the third argument to the constructor.

Try:
```
const myWorker = new Worker(
  "myworker",
  async job => {
    console.log("run");
  },
  { connection }
);
```

**Comment by combustpizza** [comment]
Thanks for the reply.

I might try this later, but I don't think that will fix the error coming from the queue.

**Comment by renozzz** [comment]
The docs do seem to be incorrect.
<img width="361" alt="bullmqType" src="https://user-images.githubusercontent.com/13501903/73604512-e84f3d80-45f6-11ea-9a60-8f7ea747bbbd.png">


Error: **Type 'Redis' is not assignable to type 'ConnectionOptions'**

**Comment by manast** [comment]
Which version are you using? I am testing to compile that code in master and it compiles just fine...

**Comment by renozzz** [comment]
I reinstalled the deps and now it does compile fine. So, the problem was with my code, since it's an existing project.

**Comment by mgan59** [comment]
Entered into this issue as I was having issues with RedisConnections being made in some deployments.  Previously we were using a single string connector `redis://username:password@dns:port`.  Trying to use that with `{ connection: { ... }}` was giving me issues.  Ended up instantiating the IORedis connection locally and passing it in.

**Comment by EvilaMany** [comment]
Still not fixed, I have tried old and new versions as well, no one did work

**Comment by manast** [comment]
@EvilaMany what is not fixed?

**Comment by nhayhoc** [comment]
same error bullmq@3.5.10, ioredis@5.3.0

**Comment by YouneLL** [comment]
> same error bullmq@3.5.10, ioredis@5.3.0

same issue: bullmq@3.6.5, ioredis@5.3.0

**Comment by manast** [comment]
@YouneLL which same issue are you referring too?

**Comment by JeffJassky** [comment]
I'm on 5.7.8 with Typescript 5.3.3 and am getting this error:
`Type 'Redis' is not assignable to type 'ConnectionOptions'.`

with just this code:
```
import { Queue } from 'bullmq'
import Redis from 'ioredis'

const queue = new Queue("myqueue", {
	connection: new Redis("my connection string")
})
```

**Comment by manast** [comment]
@JeffJassky this is strange like hell, investigating now, wonder if it is not a regression...

**Comment by manast** [comment]
@JeffJassky Ok, I just verified that you must use the latest version of ioredis 5.4.1, in order to get rid of the compiler error.

**Comment by younes101020** [comment]
Error: Type 'Redis' is not assignable to type 'ConnectionOptions'

on redis@^5.4.2, works after downgrading into ^5.4.1

**Comment by peterviergutz** [comment]
Seeing this in ioredis@5.10.0 with bullmq@5.71.0 again:

```
Error: Type 'Redis' is not assignable to type 'ConnectionOptions'
...
Type 'RedisOptions' is not assignable to type 'CommonRedisOptions'
```

Works using ioredis@5.9.3

**Comment by manast** [comment]
@peterviergutz I think the solution here is to cast to any before assigning to connection. I am not sure how we could improve the typing so that it works every time the IORedis do "breaking" changes, in the sense that they break the typescript typings even though functional speaking they did not introduce any breaking changes.
