### ISSUE TITLE
Missing lock for parent job when adding a duplicate flow job that has a child with removeOnComplete = true

### ISSUE THREAD

**Issue by Stormtv** [taskforcesh/bullmq#1099]
If you attempt to add a Flow job that already exists and the child job has already ran but the parent has not yet been ran and the child job has `removeOnComplete` set to  `true` then a duplicate child job will be created and the parent will throw an error when it is processed.

With this example you will end up with a strange state in your Redis
`bull:child-queue:test`
`bull:child-queue:wait` child job is waiting to be ran after being created again
`bull:parent-queue:active` parent job is stuck in active state until scheduler cleans it up
`bull:parent-queue:test`
`bull:parent-queue:test:dependencies` value is `bull:child-queue:test`
`bull:parent-queue:test:processed` key is `bull:child-queue:test` value is `1`

```
Error: Missing lock for job test. failed
    at Function.finishedErrors (/Users/storm/Projects/bullError/node_modules/bullmq/src/classes/scripts.ts:343:16)
    at Job.moveToFailed (/Users/storm/Projects/bullError/node_modules/bullmq/src/classes/job.ts:518:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async handleFailed (/Users/storm/Projects/bullError/node_modules/bullmq/src/classes/worker.ts:563:9)
    at async Worker.retryIfFailed (/Users/storm/Projects/bullError/node_modules/bullmq/src/classes/worker.ts:707:16)
    at async Worker.run (/Users/storm/Projects/bullError/node_modules/bullmq/src/classes/worker.ts:334:34)
```
```
failedReason: Job test has pending dependencies. finished
```

Code to reproduce the error
```ts
import { FlowProducer, JobNode, Worker } from 'bullmq'

const parentQueueName = 'parent-queue'
const childQueueName = 'child-queue'
const connection = { host: 'localhost' }

async function addJob(): Promise<JobNode> {
  const flow = new FlowProducer()
  return flow.add({
    name: 'test-parent',
    queueName: parentQueueName,
    opts: {
      jobId: 'test',
    },
    children: [
      {
        name: 'test-child',
        queueName: childQueueName,
        opts: {
          jobId: 'test',
          removeOnComplete: true,
        },
      },
    ],
  })
}

let childrenProcessor
let processedChildren = 0
const processingChildren = new Promise<void>((resolve) => {
  childrenProcessor = async (): Promise<number> => {
    console.log('Processing child job')
    processedChildren += 1
    if (processedChildren === 1) resolve()
    return 1
  }
})

const childrenWorker = new Worker(childQueueName, childrenProcessor, {
  connection,
})
await childrenWorker.waitUntilReady()

console.log('Adding Job')
await addJob()
console.log('Added Job')

await processingChildren
console.log('Done Processing')

await childrenWorker.close()
console.log('Stopped child worker')

await addJob()

const parentWorker = new Worker(
  parentQueueName,
  async (): Promise<number> => {
    console.log('Processing parent')
    return 1
  },
  { connection },
)
await parentWorker.waitUntilReady()
```

**Comment by roggervalf** [comment]
hi @Stormtv, I think that this is happening because at the time that the parent is processed, before moveToCompleted is ran, the second flow was created, so at that time the parent will have children, so the second parent is not created, the first parent is kept and when moveToCompleted is ran it throws that error, I think this is expected as the parent could not be moved to completed or failed if there are pending children

**Comment by Stormtv** [comment]
@roggervalf, The expected behavior in my opinion is that if you attempt to create a flow with an identical JobID to an existing flow then it should be ignored as well as all the children should also be ignored. The current behavior is not in line with what occurs when you create a normal job.

From the docs on Job Ids
> The main reason to be able to specify a custom id is in cases when you want to avoid duplicated jobs. Since ids must be unique, if you add a job with an existing id then that job will just be ignored and not added to the queue at all.

Thanks for looking into this.
