### ISSUE TITLE
Missing lock while waiting children

### ISSUE THREAD

**Issue by swherden** [taskforcesh/bullmq#1115]
I implemented the [Process step jobs](https://docs.bullmq.io/patterns/process-step-jobs) example from bullmq documentation. I made a little adjustment to create 10 parent jobs, just to see the behavior while processing many jobs.  The worker for the child steps are always returning a value to finish processing.
 
Now I got an Exception during runtime: `Error: Missing lock for job 32. failed`.  

My running example is:
```
import { ConnectionOptions, Job, Queue, Worker } from 'bullmq';

const connection: ConnectionOptions = {
    host: 'xyz.cloud.redislabs.com',
    port: 18091,
    password: 'passwd'
};

const parentQueueName = 'PARENT';
const childrenQueueName = 'CHILD';

const childrenQueue: Queue<any> = new Queue<any>(childrenQueueName, {
    connection: connection
});
const parentQueue: Queue<any> = new Queue<any>(parentQueueName, {
    connection: connection
});

enum Step {
    Initial,
    Second,
    Third,
    Finish
}

const parentWorker = new Worker(
    parentQueueName,
    async (job, token) => {
        let jobs: Job[] = [];
        let step = job.data.step;
        if (job.id && token)
            while (step !== Step.Finish) {
                switch (step) {
                    case Step.Initial: {
                        await doInitialStepStuff();
                        const newJob = await childrenQueue.add(
                            `child-1-${job.id}`,
                            { foo: 'bar' },
                            {
                                parent: {
                                    id: job.id,
                                    queue: `bull:${parentQueueName}`
                                }
                            }
                        );
                        jobs = [...jobs, newJob];
                        await job.update({
                            step: Step.Second
                        });
                        step = Step.Second;
                        break;
                    }
                    case Step.Second: {
                        await doSecondStepStuff();
                        const newJob = await childrenQueue.add(
                            `child-2-${job.id}`,
                            { foo: 'bar' },
                            {
                                parent: {
                                    id: job.id,
                                    queue: `${job.prefix}:${job.queueName}`
                                }
                            }
                        );
                        jobs = [...jobs, newJob];
                        await job.update({
                            step: Step.Third
                        });
                        step = Step.Third;
                        break;
                    }
                    case Step.Third: {
                        try {
                            const shouldWait = await job.moveToWaitingChildren(
                                token
                            );
                            console.log(
                                `should wait: ${shouldWait}`,
                                '--> parent job',
                                job.id ? job.id : null
                            );
                            if (!shouldWait) {
                                await job.update({
                                    step: Step.Finish
                                });
                                step = Step.Finish;
                                return Step.Finish;
                            }
                        } catch (error) {
                            console.log('error', error);
                        }
                        break;
                    }
                    default: {
                        throw new Error('invalid step');
                    }
                }
            }
    },
    { concurrency: 1, connection: connection }
);

const childWorker = new Worker(
    childrenQueueName,
    async (_job, _token) => {
        return Step.Finish;
    },
    { concurrency: 20, connection: connection }
);

if (parentWorker) console.log('Parent worker running');
if (childWorker) console.log('Child worker running');

async function start() {
    for (let index = 0; index < 10; index++) {
        parentQueue.add(`top-job-${index}`, { step: Step.Initial });
    }
}

function doInitialStepStuff() {
    // console.log('Initial');
}

function doSecondStepStuff() {
    // console.log('Second Step');
}

start();
```

This code produces the following output:
```
Parent worker running
Child worker running
should wait: false --> parent job 28
should wait: false --> parent job 29
should wait: false --> parent job 30
should wait: true --> parent job 31
should wait: false --> parent job 31
Error: Missing lock for job 31. failed
    at Function.finishedErrors (repo\node_modules\bullmq\src\classes\scripts.ts:347:16)
    at Job.moveToFailed (repo\node_modules\bullmq\src\classes\job.ts:518:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async handleFailed (repo\node_modules\bullmq\src\classes\worker.ts:563:9)
    at async Worker.retryIfFailed (repo\node_modules\bullmq\src\classes\worker.ts:707:16)
    at async Worker.run (repo\fulfillment-service\node_modules\bullmq\src\classes\worker.ts:334:34)
should wait: true --> parent job 32
should wait: false --> parent job 32
Error: Missing lock for job 32. failed
    at Function.finishedErrors (repo\node_modules\bullmq\src\classes\scripts.ts:347:16)
    at Job.moveToFailed (repo\node_modules\bullmq\src\classes\job.ts:518:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async handleFailed (repo\node_modules\bullmq\src\classes\worker.ts:563:9)
    at async Worker.retryIfFailed (repo\node_modules\bullmq\src\classes\worker.ts:707:16)
    at async Worker.run (repo\fulfillment-service\node_modules\bullmq\src\classes\worker.ts:334:34)
```

As you can see parent jobs 28, 29 and 30 are running without any errors and they must not wait for children to be finished. On the other hand, parent jobs 31 and 32 have to wait and they are producing the exception `Error: Missing lock for job ... failed`.

Do you have any explanations and solutions to get rid of this error?

Thanks a lot

**Comment by ruckonic** [comment]
You could use **flow** for this

**Comment by roggervalf** [comment]
hi @swherden, these error are expected from this pattern, this is only happening when the job is successfully moved to waiting-children, so when the processor tries to finished, it deletes the lock but it throws an error because the job is not in active status. Probably we should warn that these error could be thrown in that case

**Comment by swherden** [comment]
hi @roggervalf, yes a hint and a short explanation in the documentation would be helpful. But isn't it better that `job.moveToWaitingChildren` just returns false in that case?

**Comment by lukepolo** [comment]
just ran into this as well, we are dynamically inserting children, glad this isn't a "issue", but our error logs dont like us . 

Trying to find a way to suppress it at the moment, without hiding other errorrs.

**Comment by roggervalf** [comment]
hey guys, please review our new documentation about step job https://docs.bullmq.io/patterns/process-step-jobs when have some chance, this was solved in https://github.com/taskforcesh/bullmq/pull/1354

**Comment by happyhunter7** [comment]
@roggervalf @manast 
The example in teh docs indeed moves the job to delayed
But is also throws error Missing job lock
I guess in version 5 the (autoComplete job option was removed and that may cause eteh issue)

**Comment by roggervalf** [comment]
hi @happyhunter7 https://docs.bullmq.io/patterns/process-step-jobs#waiting-children in the same pague we have waiting children case, but also You should be aware of the use of WaitingChildrenError to be used

**Comment by happyhunter7** [comment]
@roggervalf 
My question is mostly about `moveToDelayed`
How do I safely move the same job again to delayed after this is completed so that it again can run after some custom delayed
I can't use the repeat option because every time I need a custom delay after the job is done

**Comment by happyhunter7** [comment]
should I throw a `DelayedError` after it is moved?

**Comment by happyhunter7** [comment]
In the Docs the example is confusing, because DelayedError stays in a separate switch case and not after moveToDelayed and after move to delayed it has a `break` statement which means the Delayed error will be thrown in Second stem not in first when job is moved from active to delayed... that's the most confusing part

**Comment by happyhunter7** [comment]
Oh yes I should throw the DelayedError just did that and it works as needed
I think the example in the docs needs to be fixed, since yes the Delayed error should be thrown in step one not second
@roggervalf @swherden
