### ISSUE TITLE
Webpack Loads Pro / Non Pro scripts out of order

### ISSUE THREAD

**Issue by lukepolo** [taskforcesh/bullmq#1344]
```
ReplyError: ERR user_script:328: attempt to index local 'opts' (a number value) script: c5adeaffd8ef771f6e9755bc38c2fda34095f79c, on @user_script:328.
```

Not sure exactly where this error comes from , but started to happen (bullmq pro)

**Comment by roggervalf** [comment]
hi @lukepolo, which version are you using?

**Comment by lukepolo** [comment]
BullMQ 1.86.7 , Pro: 2.3.5

**Comment by roggervalf** [comment]
@lukepolo could you please try version 2.3.9?

**Comment by lukepolo** [comment]
still failing 

```
ReplyError: ERR Error running script (call to f_c5adeaffd8ef771f6e9755bc38c2fda34095f79c): @user_script:328: user_script:328: attempt to index local 'opts' (a number value)
```

**Comment by lukepolo** [comment]
was able to get more of the error 


```
2022-08-02T13:08:14.510Z gateway:CleanSnapshots <4> Job Failed:  CleanSnapshots ReplyError: ERR Error running script (call to f_288b28eb7005ee2410a2d8dc5fa1aa6cdaf80813): @user_script:337: user_script:337: attempt to index local 'opts' (a number value)
    at parseError (/opt/qumulex/app.js:2:1404585)
    at parseType (/opt/qumulex/app.js:2:1404594) {
  command: {
    name: 'evalsha',
    args: [
      '288b28eb7005ee2410a2d8dc5fa1aa6cdaf80813',
      '12',
      'maintenance:DeleteSnapshots:wait',
      'maintenance:DeleteSnapshots:active',
      'maintenance:DeleteSnapshots:priority',
      'maintenance:DeleteSnapshots:events',
      'maintenance:DeleteSnapshots:stalled',
      'maintenance:DeleteSnapshots:limiter',
      'maintenance:DeleteSnapshots:delayed',
      'maintenance:DeleteSnapshots:delay',
      'maintenance:DeleteSnapshots:completed',
      'maintenance:DeleteSnapshots:CleanSnapshots',
      'maintenance:DeleteSnapshots:meta',
      'maintenance:DeleteSnapshots:metrics:completed',
      'CleanSnapshots',
      '1659445694494',
      'returnvalue',
      '{"result":[],"job":"CleanSnapshots"}',
      'completed',
      <Buffer de 00 01 a5 63 6f 75 6e 74 00>,

```

**Comment by roggervalf** [comment]
thank you @lukepolo for the stack trace, so this is pointing to moveToFinished script but from your example this is using the moveToFinished base script, no the pro one, because the pro one has an extra arg value that I could not see, so wondering if your are using bullmq-pro and bullmq together. For reference, bullmq moveToFinished receives 12 keys and 9 args (the 9th is opts), bullmq-pro receives 12 keys and 10 args (the 10th is opts)

**Comment by lukepolo** [comment]
we have multiple microservices touching the same redis instance but, each is using the prefix option bull providers.

Otherwise, no the service runs independently and only uses bullmq pro.

**Comment by lukepolo** [comment]
looks like i have the 12 args this time though


```
2022-08-02T22:00:29.881Z gateway:CleanSnapshots <4> Job Failed:  CleanSnapshots ReplyError: ERR Error running script (call to f_288b28eb7005ee2410a2d8dc5fa1aa6cdaf80813): @user_script:337: user_script:337: attempt to index local 'opts' (a number value)
    at parseError (/opt/qumulex/app.js:2:1171163)
    at parseType (/opt/qumulex/app.js:2:1171172) {
  command: {
    name: 'evalsha',
    args: [
      '288b28eb7005ee2410a2d8dc5fa1aa6cdaf80813',
      '12',
      'maintenance:DeleteSnapshots:wait',
      'maintenance:DeleteSnapshots:active',
      'maintenance:DeleteSnapshots:priority',
      'maintenance:DeleteSnapshots:events',
      'maintenance:DeleteSnapshots:stalled',
      'maintenance:DeleteSnapshots:limiter',
      'maintenance:DeleteSnapshots:delayed',
      'maintenance:DeleteSnapshots:delay',
      'maintenance:DeleteSnapshots:completed',
      'maintenance:DeleteSnapshots:CleanSnapshots',
      'maintenance:DeleteSnapshots:meta',
      'maintenance:DeleteSnapshots:metrics:completed',
      'CleanSnapshots',
      '1659477629864',
      'returnvalue',
      '{"result":[],"job":"CleanSnapshots"}',
      'completed',
      <Buffer de 00 01 a5 63 6f 75 6e 74 00>,
      '{"jobId":"CleanSnapshots","val":"{\\"result\\":[],\\"job\\":\\"CleanSnapshots\\"}"}',
      '1',
      'maintenance:DeleteSnapshots:',
      <Buffer de 00 08 a5 74 6f 6b 65 6e d9 24 33 65 35 32 31 33 39 66 2d 36 37 61 38 2d 34 39 30 36 2d 61 62 64 39 2d 38 61 64 31 64 64 35 34 34 63 32 63 ac 6c 6f ... 79 more bytes>
    ]
  }
}
```

**Comment by lukepolo** [comment]
are you guys using webpack when testing? ill try to create a small project to see if it still happens. (our projects are ah quite extensive 😆 )

**Comment by roggervalf** [comment]
no we don't use webpsck for testing, it's same testing config as in bullmq. Did you recently add webpack to your project?

**Comment by lukepolo** [comment]
No , but something has changed and not exactly sure what

**Comment by lukepolo** [comment]
Im able to reproduce now with the repo above, it seems like sharing the redis connection has something todo with it? 

```
ReplyError: WRONGTYPE Operation against a key holding the wrong kind of value script: 4d7b090b56fe5384faa95e756e1375277faea973, on @user_script:108.
    at Redis.moveToActive (/Users/luke/Code/opensource/bullmq/dist/app.js:31645:34)
    at ScriptsPro.moveToActive (/Users/luke/Code/opensource/bullmq/dist/app.js:1487:37)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async WorkerPro.moveToActive (/Users/luke/Code/opensource/bullmq/dist/app.js:1725:35) {
  command: {
    name: 'evalsha',
    args: [
      '4d7b090b56fe5384faa95e756e1375277faea973',
      '8',
      'lukepolo-2:default:wait',
      'lukepolo-2:default:active',
      'lukepolo-2:default:priority',
      'lukepolo-2:default:events',
      'lukepolo-2:default:stalled',
      'lukepolo-2:default:limiter',
      'lukepolo-2:default:delayed',
      'lukepolo-2:default:delay',
      'lukepolo-2:default:',
      '1659542563283',
      '100',
      <Buffer de 00 04 a5 74 6f 6b 65 6e d9 24 32 61 36 64 66 37 33 33 2d 32 35 32 38 2d 34 62 62 37 2d 39 33 34 35 2d 63 32 33 38 33 66 35 30 61 33 33 32 ac 6c 6f ... 29 more bytes>
    ]
  }
}
```

**Comment by roggervalf** [comment]
hey @lukepolo, I took a look on your repo and even that it is using the pro package, it is using the bullmq moveToFinished base script where stalled key is expected to be a set, not a zset as in the pro version, but the general problem here is that for some reason it is using the legacy scripts instead of the new ones that comes in the pro version

**Comment by roggervalf** [comment]
sorry for the delay @lukepolo, when I tried your example without webpack, it is working ok, so it seems like it's a webpack symptom

**Comment by manast** [comment]
How does it look like in the target installation directory? can you check that the PRO lua scripts are in its correctly location?

**Comment by lukepolo** [comment]
```
LOADING node_modules/bullmq/dist/esm/commands/includes/destructureJobKey.lua
LOADING node_modules/bullmq/dist/esm/commands/includes/destructureJobKey.lua
LOADING node_modules/bullmq/dist/esm/commands/includes/getTargetQueueList.lua
LOADING node_modules/bullmq/dist/esm/commands/includes/getTargetQueueList.lua
LOADING node_modules/bullmq/dist/esm/commands/includes/trimEvents.lua
LOADING node_modules/bullmq/dist/esm/commands/includes/trimEvents.lua
LOADING node_modules/bullmq/dist/esm/commands/includes/updateParentDepsIfNeeded.lua
LOADING node_modules/bullmq/dist/esm/commands/includes/updateParentDepsIfNeeded.lua
LOADING node_modules/bullmq/dist/esm/commands/includes/checkItemInList.lua
LOADING node_modules/bullmq/dist/esm/commands/includes/checkItemInList.lua
LOADING node_modules/bullmq/dist/esm/commands/includes/batches.lua
LOADING node_modules/bullmq/dist/esm/commands/includes/batches.lua
LOADING node_modules/bullmq/dist/esm/commands/includes/getTargetQueueList.lua
LOADING node_modules/bullmq/dist/esm/commands/includes/removeJob.lua
LOADING node_modules/bullmq/dist/esm/commands/includes/getTargetQueueList.lua
LOADING node_modules/bullmq/dist/esm/commands/includes/removeJob.lua
LOADING node_modules/bullmq/dist/esm/commands/includes/removeJobsByMaxAge.lua
LOADING node_modules/bullmq/dist/esm/commands/includes/removeJobsByMaxAge.lua
LOADING node_modules/bullmq/dist/esm/commands/includes/removeJobsByMaxCount.lua
LOADING node_modules/bullmq/dist/esm/commands/includes/removeJobsByMaxCount.lua
LOADING node_modules/bullmq/dist/esm/commands/includes/trimEvents.lua
LOADING node_modules/bullmq/dist/esm/commands/includes/trimEvents.lua
LOADING node_modules/bullmq/dist/esm/commands/includes/trimEvents.lua
LOADING node_modules/bullmq/dist/esm/commands/includes/collectMetrics.lua
LOADING node_modules/bullmq/dist/esm/commands/includes/trimEvents.lua
LOADING node_modules/bullmq/dist/esm/commands/includes/collectMetrics.lua
LOADING node_modules/bullmq/dist/esm/commands/includes/destructureJobKey.lua
LOADING node_modules/bullmq/dist/esm/commands/includes/updateParentDepsIfNeeded.lua
LOADING node_modules/bullmq/dist/esm/commands/includes/removeJob.lua
LOADING node_modules/bullmq/dist/esm/commands/includes/removeJobsByMaxAge.lua
LOADING node_modules/bullmq/dist/esm/commands/includes/removeJobsByMaxCount.lua
LOADING node_modules/bullmq/dist/esm/commands/includes/removeParentDependencyKey.lua
LOADING node_modules/bullmq/dist/esm/commands/includes/destructureJobKey.lua
LOADING node_modules/bullmq/dist/esm/commands/includes/updateParentDepsIfNeeded.lua
LOADING node_modules/bullmq/dist/esm/commands/includes/removeJob.lua
LOADING node_modules/bullmq/dist/esm/commands/includes/removeJobsByMaxAge.lua
LOADING node_modules/bullmq/dist/esm/commands/includes/removeJobsByMaxCount.lua
LOADING node_modules/bullmq/dist/esm/commands/includes/removeParentDependencyKey.lua
LOADING node_modules/bullmq/dist/esm/commands/includes/getTargetQueueList.lua
LOADING node_modules/bullmq/dist/esm/commands/includes/getTargetQueueList.lua
LOADING node_modules/bullmq/dist/esm/commands/includes/batches.lua
LOADING node_modules/bullmq/dist/esm/commands/includes/getTargetQueueList.lua
LOADING node_modules/bullmq/dist/esm/commands/includes/batches.lua
LOADING node_modules/bullmq/dist/esm/commands/includes/getTargetQueueList.lua
LOADING node_modules/bullmq/dist/esm/commands/includes/getTargetQueueList.lua
LOADING node_modules/bullmq/dist/esm/commands/includes/getTargetQueueList.lua
```

it doesn't seem to ever try to load the pro scripts.

**Comment by lukepolo** [comment]
it seems like a race condition thing: 




First Run
```
open http://localhost:3001/queues
LOADING PATH node_modules/@taskforcesh/bullmq-pro/dist/esm/commands
LOADING PATH node_modules/bullmq/dist/esm/commands
LOADING PATH node_modules/@taskforcesh/bullmq-pro/dist/esm/commands
LOADING PATH node_modules/bullmq/dist/esm/commands
  node_modules/@taskforcesh/bullmq-pro/dist/esm/commands 19
  node_modules/bullmq/dist/esm/commands 27
  node_modules/@taskforcesh/bullmq-pro/dist/esm/commands 19
  node_modules/bullmq/dist/esm/commands 27
[node_modules/@taskforcesh/bullmq-pro/dist/esm/commands]         addJob loaded in cache already
[node_modules/@taskforcesh/bullmq-pro/dist/esm/commands]         extendLock loaded in cache already
[node_modules/@taskforcesh/bullmq-pro/dist/esm/commands]         getState loaded in cache already
[node_modules/@taskforcesh/bullmq-pro/dist/esm/commands]         getStateV2 loaded in cache already
[node_modules/@taskforcesh/bullmq-pro/dist/esm/commands]         moveStalledJobsToWait loaded in cache already
[node_modules/@taskforcesh/bullmq-pro/dist/esm/commands]         moveToActive loaded in cache already
[node_modules/@taskforcesh/bullmq-pro/dist/esm/commands]         moveToDelayed loaded in cache already
[node_modules/@taskforcesh/bullmq-pro/dist/esm/commands]         moveToFinished loaded in cache already
[node_modules/@taskforcesh/bullmq-pro/dist/esm/commands]         retryJob loaded in cache already
[node_modules/@taskforcesh/bullmq-pro/dist/esm/commands]         retryJobs loaded in cache already
[node_modules/@taskforcesh/bullmq-pro/dist/esm/commands]         updateDelaySet loaded in cache already
LOADING PATH node_modules/bullmq/dist/esm/commands
[node_modules/bullmq/dist/esm/commands]         addJob loaded in cache already
[node_modules/bullmq/dist/esm/commands]         extendLock loaded in cache already
[node_modules/bullmq/dist/esm/commands]         getState loaded in cache already
[node_modules/bullmq/dist/esm/commands]         getStateV2 loaded in cache already
[node_modules/bullmq/dist/esm/commands]         moveStalledJobsToWait loaded in cache already
[node_modules/bullmq/dist/esm/commands]         moveToActive loaded in cache already
[node_modules/bullmq/dist/esm/commands]         moveToDelayed loaded in cache already
[node_modules/bullmq/dist/esm/commands]         moveToFinished loaded in cache already
[node_modules/bullmq/dist/esm/commands]         retryJob loaded in cache already
[node_modules/bullmq/dist/esm/commands]         retryJobs loaded in cache already
[node_modules/bullmq/dist/esm/commands]         updateDelaySet loaded in cache already
```



Second Run 

```
open http://localhost:3001/queues
LOADING PATH node_modules/@taskforcesh/bullmq-pro/dist/esm/commands
LOADING PATH node_modules/bullmq/dist/esm/commands
LOADING PATH node_modules/@taskforcesh/bullmq-pro/dist/esm/commands
LOADING PATH node_modules/bullmq/dist/esm/commands
  node_modules/@taskforcesh/bullmq-pro/dist/esm/commands 19
  node_modules/bullmq/dist/esm/commands 27
  node_modules/@taskforcesh/bullmq-pro/dist/esm/commands 19
  node_modules/bullmq/dist/esm/commands 27
LOADING PATH node_modules/bullmq/dist/esm/commands
[node_modules/bullmq/dist/esm/commands]         addJob loaded in cache already
[node_modules/bullmq/dist/esm/commands]         extendLock loaded in cache already
[node_modules/bullmq/dist/esm/commands]         getState loaded in cache already
[node_modules/bullmq/dist/esm/commands]         getStateV2 loaded in cache already
[node_modules/bullmq/dist/esm/commands]         moveStalledJobsToWait loaded in cache already
[node_modules/bullmq/dist/esm/commands]         moveToActive loaded in cache already
[node_modules/bullmq/dist/esm/commands]         moveToDelayed loaded in cache already
[node_modules/bullmq/dist/esm/commands]         moveToFinished loaded in cache already
[node_modules/bullmq/dist/esm/commands]         retryJob loaded in cache already
[node_modules/bullmq/dist/esm/commands]         retryJobs loaded in cache already
[node_modules/bullmq/dist/esm/commands]         updateDelaySet loaded in cache already
[node_modules/@taskforcesh/bullmq-pro/dist/esm/commands]         addJob loaded in cache already
[node_modules/@taskforcesh/bullmq-pro/dist/esm/commands]         extendLock loaded in cache already
[node_modules/@taskforcesh/bullmq-pro/dist/esm/commands]         getState loaded in cache already
[node_modules/@taskforcesh/bullmq-pro/dist/esm/commands]         getStateV2 loaded in cache already
[node_modules/@taskforcesh/bullmq-pro/dist/esm/commands]         moveStalledJobsToWait loaded in cache already
[node_modules/@taskforcesh/bullmq-pro/dist/esm/commands]         moveToActive loaded in cache already
[node_modules/@taskforcesh/bullmq-pro/dist/esm/commands]         moveToDelayed loaded in cache already
[node_modules/@taskforcesh/bullmq-pro/dist/esm/commands]         moveToFinished loaded in cache already
[node_modules/@taskforcesh/bullmq-pro/dist/esm/commands]         retryJob loaded in cache already
[node_modules/@taskforcesh/bullmq-pro/dist/esm/commands]         retryJobs loaded in cache already
[node_modules/@taskforcesh/bullmq-pro/dist/esm/commands]         updateDelaySet loaded in cache already
```

**Comment by lukepolo** [comment]
changed the load function ` if (!client[command.name] || pathname.includes('pro')) {` and it seems to work .

**Comment by manast** [comment]
It seems like the order is wrong, it should load first the BullMQ scripts, and then the BullMQ Pro scripts, as some scripts will be overrided by the PRO version. I do not understand though how webpack could affect such order...

**Comment by lukepolo** [comment]
i haven't dug too much deeper, but it seems they are being added in parallel

**Comment by manast** [comment]
> i haven't dug too much deeper, but it seems they are being added in parallel

If that happens then it will not work properly. Do you get a different result when not using webpack?

**Comment by lukepolo** [comment]
not sure ill test, my hunch is it's a bug regardless of using webpack / non webpack.

**Comment by manast** [comment]
The repo you provided above, does it reproduce the issue for you? because @roggervalf looked into it but could not reproduce it, or maybe you have some simpler case that we can look into?

**Comment by lukepolo** [comment]
ill try it without webpack to validate, but im not sure how much simpler i can get 😆

**Comment by lukepolo** [comment]
removing webpack does seem to resolve it, i can reproduce with webpack pretty easily, but ts-node doesn't seem to reproduce it.

**Comment by lukepolo** [comment]
The biggest difference so far is one loads with ESM the other with CJS

**Comment by lukepolo** [comment]
OH! just happened with ts-node now!!

```
ReplyError: ERR Error running script (call to f_4d7b090b56fe5384faa95e756e1375277faea973): @user_script:108: WRONGTYPE Operation against a key holding the wrong kind of value
    at ScriptsPro.moveToActive (/Users/luke/Code/opensource/bullmq/node_modules/@taskforcesh/bullmq-pro/src/classes/scripts-pro.ts:133:40)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async WorkerPro.moveToActive (/Users/luke/Code/opensource/bullmq/node_modules/@taskforcesh/bullmq-pro/src/classes/worker-pro.ts:113:29) {
  command: {
    name: 'evalsha',
    args: [
      '4d7b090b56fe5384faa95e756e1375277faea973',
      '8',
      'lukepolo-2:default:wait',
      'lukepolo-2:default:active',
      'lukepolo-2:default:priority',
      'lukepolo-2:default:events',
      'lukepolo-2:default:stalled',
      'lukepolo-2:default:limiter',
      'lukepolo-2:default:delayed',
      'lukepolo-2:default:delay',
      'lukepolo-2:default:',
      '1660746565071',
      '4829',
      <Buffer de 00 04 a5 74 6f 6b 65 6e d9 24 37 63 34 39 34 37 35 37 2d 37 38 35 36 2d 34 32 34 37 2d 38 33 37 35 2d 37 62 36 65 34 30 39 37 33 34 33 39 ac 6c 6f ... 29 more bytes>
    ]
  }
}
ReplyError: ERR Error running script (call to f_4d7b090b56fe5384faa95e756e1375277faea973): @user_script:108: WRONGTYPE Operation against a key holding the wrong kind of value
    at ScriptsPro.moveToActive (/Users/luke/Code/opensource/bullmq/node_modules/@taskforcesh/bullmq-pro/src/classes/scripts-pro.ts:133:40)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async WorkerPro.moveToActive (/Users/luke/Code/opensource/bullmq/node_modules/@taskforcesh/bullmq-pro/src/classes/worker-pro.ts:113:29) {
  command: {
    name: 'evalsha',
    args: [
      '4d7b090b56fe5384faa95e756e1375277faea973',
      '8',
      'lukepolo-2:default:wait',
      'lukepolo-2:default:active',
      'lukepolo-2:default:priority',
      'lukepolo-2:default:events',
      'lukepolo-2:default:stalled',
      'lukepolo-2:default:limiter',
      'lukepolo-2:default:delayed',
      'lukepolo-2:default:delay',
      'lukepolo-2:default:',
      '1660746565071',
      '4829',
      <Buffer de 00 04 a5 74 6f 6b 65 6e d9 24 37 63 34 39 34 37 35 37 2d 37 38 35 36 2d 34 32 34 37 2d 38 33 37 35 2d 37 62 36 65 34 30 39 37 33 34 33 39 ac 6c 6f ... 29 more bytes>
    ]
  }
}


```

**Comment by lukepolo** [comment]
It doesn't happen 100% of the time, (def a race condition) 

```
LOADING BullMQ
LOADING BullMQ-Pro
LOADING BullMQ-Pro
LOADING BullMQ
LOADING BullMQ
```

**Comment by sebmellen** [comment]
@lukepolo have you had any luck debugging/fixing this?

**Comment by roggervalf** [comment]
hey guys, please try version 4 https://github.com/taskforcesh/bullmq/blob/master/docs/gitbook/bullmq-pro/changelog.md#400-2022-10-27

**Comment by roggervalf** [comment]
looks like it was solved
