### ISSUE TITLE
Error: Must use import to load ES module

### ISSUE THREAD

**Issue by theoilie** [taskforcesh/bullmq#1424]
Hello,

I'm seeing this error when a job fails while using `waitUntilFinished`:
```
Error: Must use import to load ES Module: /usr/src/app/node_modules/bullmq/node_modules/get-port/index.js
require() of ES modules is not supported.
require() of /usr/src/app/node_modules/bullmq/node_modules/get-port/index.js from /usr/src/app/node_modules/bullmq/dist/cjs/classes/child-pool.js is an ES module file as it is a .js file whose nearest parent package.json contains \"type\": \"module\" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove \"type\": \"module\" from /usr/src/app/node_modules/bullmq/node_modules/get-port/package.json.

    at QueueEvents.onFailed (/usr/src/app/node_modules/bullmq/src/classes/job.ts:851:16)
    at QueueEvents.emit (events.js:400:28)
    at QueueEvents.emit (domain.js:475:12)
    at QueueEvents.emit (/usr/src/app/node_modules/bullmq/src/classes/queue-base.ts:103:20)
    at QueueEvents.emit (/usr/src/app/node_modules/bullmq/src/classes/queue-events.ts:196:18)
    at QueueEvents.consumeEvents (/usr/src/app/node_modules/bullmq/src/classes/queue-events.ts:288:18)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async QueueEvents.run (/usr/src/app/node_modules/bullmq/src/classes/queue-events.ts:241:9)
```

Code to reproduce is something like:
```
const queue = new Queue(...)
const worker = new Worker(...)
const queueEvents = new QueueEvents(...)
const job = await queue.add('job-name', {})
await job.waitUntilFinished(queueEvents)
```

Then, when the job fails, this error is thrown. This is with BullMQ v1.91.1 and Node v14.20.0. Any advise would be greatly appreciated 🙂

**Comment by theoilie** [comment]
[This](https://github.com/taskforcesh/bullmq/blob/master/src/classes/child-pool.ts#L24) appears to be the offending line. Can this be changed to import at the top instead of calling `import()` in the middle of the file?

**Comment by manast** [comment]
Interesting. Supposedly this change https://github.com/taskforcesh/bullmq/pull/1374 should have made it more compatible but I guess that is not the case. What do you think @boredland ?
