### ISSUE TITLE
Job is `undefined` in worker `failed` listener

### ISSUE THREAD

**Issue by jstayton** [taskforcesh/bullmq#1495]
This doesn't happen frequently, but every so often, this error occurs in my worker's `failed` listener:

```
TypeError: Cannot read properties of undefined (reading 'attemptsMade')
  File "/srv/build/1666358956/src/jobs/base/worker_creator.js", line 30, col 33, in Worker.<anonymous>
    const isLastAttempt = job.attemptsMade === job.opts.attempts
  File "node:events", line 520, col 28, in Worker.emit
  File "node:domain", line 475, col 12, in Worker.emit
  File "/srv/build/1666358956/node_modules/bullmq/dist/cjs/classes/queue-base.js", line 77, col 26, in Worker.emit
    return super.emit(event, ...args);
  File "/srv/build/1666358956/node_modules/bullmq/dist/cjs/classes/worker.js", line 69, col 22, in Worker.emit
    return super.emit(event, ...args);
  File "/srv/build/1666358956/node_modules/bullmq/dist/cjs/classes/worker.js", line 499, col 42, in <anonymous>
    failedJobs.forEach((job) => this.emit('failed', job, new Error('job stalled more than allowable limit'), 'active'));
  File "/srv/build/1666358956/src/jobs/base/worker_creator.js", in Array.forEach
  File "/srv/build/1666358956/node_modules/bullmq/dist/cjs/classes/worker.js", line 499, col 20, in Worker.notifyFailedJobs
    failedJobs.forEach((job) => this.emit('failed', job, new Error('job stalled more than allowable limit'), 'active'));
  File "/srv/build/1666358956/node_modules/bullmq/dist/cjs/classes/worker.js", line 492, col 22, in Worker.moveStalledJobsToWait
    this.notifyFailedJobs(await Promise.all(jobPromises));
  File "node:internal/process/task_queues", line 96, col 5, in processTicksAndRejections
```

Here's a condensed version of the code in question:

```js
const worker = new Worker(...)

worker.on('failed', (job, error) => {
  // This is where the error occurs due to `job` being `undefined`:
  const isLastAttempt = job.attemptsMade === job.opts.attempts

  // More code...
})
```

[The docs](https://api.docs.bullmq.io/interfaces/WorkerListener.html#failed) seem to say that `job` should always be an instance of the `Job` class. Am I reading that right? Or should I guard against `job` being `undefined` in my code?

This is running BullMQ v2.1.1. Thanks for your help!

**Comment by jstayton** [comment]
I added some logging to capture the associated `error`:

```
Error: job stalled more than allowable limit
    at /srv/build/1668078949/node_modules/bullmq/dist/cjs/classes/worker.js:497:62
    at Array.forEach (<anonymous>)
    at Worker.notifyFailedJobs (/srv/build/1668078949/node_modules/bullmq/dist/cjs/classes/worker.js:497:20)
    at Worker.moveStalledJobsToWait (/srv/build/1668078949/node_modules/bullmq/dist/cjs/classes/worker.js:490:22)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Worker.checkConnectionError (/srv/build/1668078949/node_modules/bullmq/dist/cjs/classes/queue-base.js:118:20)
    at async Worker.runStalledJobsCheck (/srv/build/1668078949/node_modules/bullmq/dist/cjs/classes/worker.js:474:17)
```

**Comment by manast** [comment]
So unfortunately if we use ```removeOnFailed```, there is a case when the job has stalled more than the allowed limit where we end in a situation where the job has failed AND is removed in the same script. Although it would theoretically be possible to return the job data in the "checkStalledJobs" script, there is a risk that if there are many jobs that got stalled, and the data is large, we end up consuming too much ram memory. So I think that the best, for the time being, is to merge @roggervalf fix and force the listeners of this event to check if job is undefined before doing anything with it.

**Comment by jstayton** [comment]
I'm good with checking for `undefined` before proceeding. 👍🏻 Thanks!
