### ISSUE TITLE
NodeJS cluster mode causing issues with job locks

### ISSUE THREAD

**Issue by theoilie** [taskforcesh/bullmq#1507]
Enabling NodeJS cluster (not redis cluster) has made Bull become unreliable. Here's our basic setup for each queue, assuming we have a concurrency of 5 per cluster child process and, for example, 2 cluster child processes on the server (plus the primary process, which just routes traffic and doesn't initialize any queues or workers):

```ts
const connection = {
    host: 'localhost',
    port: 6379
}
const queue = new Queue('test-queue', {
    connection,
    defaultJobOptions: {
        removeOnComplete: 500,
        removeOnFail: 500
    }
})
const worker = new Worker(
    'test-queue',
    async (job) => {
        // Simple job processing here - nothing that blocks the event loop
        return {}
    },
    {
        connection,
        concurrency: 5
    }
)
```

Here are the main issues, all seeming to be related to locks with multiple workers:

1. Every job on bull-board shows that it's on attempt 2 (I confirmed in their code and this is reflecting `job.attemptsMade`), regardless of success or failure. This is consistent for every job in every queue, even though most of them complete successfully and used to only have 1 `attemptsMade` prior to enabling NodeJS cluster.
2. "Missing lock for job" errors started happening intermittently. Example:
```
Error: Missing lock for job 193426. failed
    at Scripts.finishedErrors (/usr/src/app/node_modules/bullmq/dist/cjs/classes/scripts.js:206:24)
    at Job.moveToFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/job.js:343:32)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async handleFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:320:17)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:455:24)
```

Are there any race conditions that could cause issues with workers fighting for the same locks from separate processes on the same server?

**Comment by manast** [comment]
Could you please provide the complete test code including the NodeJS clusterization so that we can reproduce the issue?

**Comment by manast** [comment]
(and BullMQ version)

**Comment by theoilie** [comment]
This is with BullMQ v1.91.1. I made [this standalone repo](https://github.com/theoilie/cluster-bull) (it just requires redis to be running locally) to easily run this in a way that very closely resembles the environment I'm seeing it happen in. The README has screenshots of the issue. Also the code for reference:

```ts
import { createBullBoard } from '@bull-board/api'
import { BullAdapter } from '@bull-board/api/bullAdapter'
import { ExpressAdapter } from '@bull-board/express'
import { Queue, Worker } from 'bullmq'
import cluster from 'cluster'
import express from 'express'

const REDIS_HOST = '127.0.0.1'
const REDIS_PORT = 6379
const PORT = 5005
const CLUSTER_ENABLED = false
const NUM_CLUSTER_WORKERS = 2
const BULL_CONCURRENCY_PER_PROCESS = 5

const log = (msg: any) => {
  const worker = cluster.worker?.id ?? 'primary'
  console.log(`[worker ${worker}] ${msg}`)
}

const getRandomNum = (min: number, max: number) => {
  return Math.floor(Math.random() * (max - min + 1)) + min
}

const addJobsToQueue = async (queue: Queue) => {
  while (true) {
    await queue.add('test job', { randomNumber: getRandomNum(0, 100) })
    await timeout(getRandomNum(1000, 10_000))
  }
}

const timeout = (ms: number) => {
  return new Promise((resolve) => setTimeout(resolve, ms))
}

// The primary process performs one-time validation and spawns worker processes that each run the Express app
const startAppForPrimary = async () => {
  log(`Primary process with pid=${process.pid} is running`)

  // Spawn cluster workers (child processes of the primary)
  log(`Spawning ${NUM_CLUSTER_WORKERS} processes to run the Express app. Each will have its own queue worker to process ${BULL_CONCURRENCY_PER_PROCESS} Bull jobs concurrently...`)
  for (let i = 0; i < NUM_CLUSTER_WORKERS; i++) {
    cluster.fork()
  }
}

// Workers don't share memory - each is its own process running its own Express app and Redis connections for Bull queues
const startAppForWorker = async () => {
  log(`Worker process with pid=${process.pid} and worker is running`)
  await startApp()
}

const startAppWithoutCluster = async () => {
  log(`Starting app with cluster mode disabled...`)
  await startApp()
}

const startApp = async () => {
  // Create Express server
  const app = express()
  app.listen(PORT)

  // Make a queue with a worker
  const queueName = 'test-queue'
  const connection = {
    host: REDIS_HOST,
    port: REDIS_PORT
  } as any
  const queue = new Queue(queueName, { connection })
  await queue.obliterate({ force: true })
  new Worker(
    queueName,
    async (job) => {
      await timeout(getRandomNum(1000, 10_000))
      return { randomNumber: job.data.randomNumber }
    },
    {
      connection,
      concurrency: BULL_CONCURRENCY_PER_PROCESS
    }
  )

  // Setup `/dashboard` endpoint to view queue info
  const serverAdapter = new ExpressAdapter()
  createBullBoard({
    queues: [new BullAdapter(queue)],
    serverAdapter
  })
  serverAdapter.setBasePath('/dashboard')
  app.use('/dashboard', serverAdapter.getRouter())

  await addJobsToQueue(queue)
}

if (!CLUSTER_ENABLED) startAppWithoutCluster()
else if (cluster.isMaster) startAppForPrimary()
else if (cluster.isWorker) startAppForWorker()
else throw new Error("Can't determine if process is primary or worker in cluster")
```

**Comment by manast** [comment]
How long until the issue starts appearing?
Btw, have you tried with newer versions of BullMQ?

**Comment by manast** [comment]
![image](https://user-images.githubusercontent.com/95200/199691768-9402242e-1211-49b4-babd-6266b6d6edff.png)
![image](https://user-images.githubusercontent.com/95200/199691817-4a3c6ba5-1656-4cc9-81d4-14d566ca53fe.png)

**Comment by manast** [comment]
392 jobs and still no errors.

**Comment by manast** [comment]
I will leave it running but I do not expect it to fail.

**Comment by theoilie** [comment]
Hmm, strange - I saw the error on the first job. If our code is the same, the only difference I see here is yarn vs npm and the machine it's running on. What Node version was this running? I'm seeing these issues on Node v14.19.1 and Redis server 7.0.4.

I searched through the changelog and didn't see anything that looked too relevant so avoided updating but will get to that soon.

**Comment by theoilie** [comment]
I tried permutations of yarn and npm with updated Node versions up to v18.12.0 and did see some successful runs without the error, but if I restart a few times I see the issue reproduce regardless of environment permutation.

Here's a more reliable way to reproduce: I made cluster workers respawn when they die (which our actual app has as well) and consistently see errors whenever a worker respawns:
1. `git pull` to get the worker respawning logic and `yarn start:dev`
2. Copy the PID that was logged for any worker and in another terminal run `kill <pid>`
3. Errors should be logged. You can repeat this as many times as you'd like and should see an error every time

<img width="1106" alt="Screen Shot 2022-11-03 at 11 57 51 AM" src="https://user-images.githubusercontent.com/4657956/199770924-a347ff87-cb41-49ba-9296-d11891d19f6a.png">

**Comment by manast** [comment]
I tried your updated code and instructions and I was able to reproduce the issue. Furthermore, I examined the logs of Redis monitor, and what I saw did not make any sense. It seemed as if a different worker instance was trying to complete a job that was started by another worker instance. Almost as if the worker instance were shared in some very strange way.
I simplified the code by removing all Bullboard, and express related code, and tried again and I cannot reproduce the issue anymore. So I do not know what kind of stuff express or bullboard introduce in this whole thing but it is beyond my understanding, processes should be completely isolated from each other, yet it seems like something bleeds between them in this case.

Anyway, I am not able to reproduce the issue anymore with this code:
```ts

import { Queue, Worker } from 'bullmq';
import cluster from 'cluster';

const REDIS_HOST = '127.0.0.1';
const REDIS_PORT = 6379;
const CLUSTER_ENABLED = true;
const NUM_CLUSTER_WORKERS = 2;
const BULL_CONCURRENCY_PER_PROCESS = 5;

const log = (msg: any) => {
  const worker = cluster.worker?.id ?? 'primary';
  console.log(`[worker ${worker}] ${msg}`);
};

const getRandomNum = (min: number, max: number) => {
  return Math.floor(Math.random() * (max - min + 1)) + min;
};

const addJobsToQueue = async (queue: Queue) => {
  while (true) {
    await queue.add('test job', { randomNumber: getRandomNum(0, 100) });
    await timeout(getRandomNum(1000, 10_000))
  }
};

const timeout = (ms: number) => {
  return new Promise((resolve) => setTimeout(resolve, ms));
};

// The primary process performs one-time validation and spawns worker processes that each run the Express app
const startAppForPrimary = async () => {
  log(`Primary process with pid=${process.pid} is running`);

  // Spawn cluster workers (child processes of the primary)
  log(
    `Spawning ${NUM_CLUSTER_WORKERS} processes to run the Express app. Each will have its own queue worker to process ${BULL_CONCURRENCY_PER_PROCESS} Bull jobs concurrently...`,
  );
  for (let i = 0; i < NUM_CLUSTER_WORKERS; i++) {
    cluster.fork();
  }

  // Respawn workers when they die
  cluster.on('exit', (worker, code, signal) => {
    log(
      `Worker process with pid=${worker.process.pid} died because ${
        signal || code
      }. Respawning...`,
    );
    cluster.fork();
  });
};

// Workers don't share memory - each is its own process running its own Express app and Redis connections for Bull queues
const startAppForWorker = async () => {
  log(`Worker process with pid=${process.pid} and worker is running`);
  await startApp();
};

const startAppWithoutCluster = async () => {
  log(`Starting app with cluster mode disabled...`);
  await startApp();
};

const startApp = async () => {
  // Make a queue with a worker
  const queueName = 'test-queue';
  const connection = {
    host: REDIS_HOST,
    port: REDIS_PORT,
  } as any;
  const queue = new Queue(queueName, { connection });
  //await queue.obliterate({ force: true });
  new Worker(
    queueName,
    async (job) => {
      await timeout(getRandomNum(1000, 10_000));
      return { randomNumber: job.data.randomNumber };
    },
    {
      connection,
      concurrency: BULL_CONCURRENCY_PER_PROCESS,
    },
  );

  await addJobsToQueue(queue);
};

if (!CLUSTER_ENABLED) startAppWithoutCluster();
else if (cluster.isMaster) startAppForPrimary();
else if (cluster.isWorker) startAppForWorker();
else
  throw new Error("Can't determine if process is primary or worker in cluster");
```

**Comment by theoilie** [comment]
Thanks for testing that. I played around with it some more and was able to make a minimal example that works with Express+BullBoard. I also found that it still fails without Express+BullBoard in 2 scenarios, which I added variables to demo in the snippet at the bottom of this message. This can be tested by setting `SHOULD_TRIGGER_ERROR_PATH1` and `SHOULD_TRIGGER_ERROR_PATH2` to true or false and doing the following flow:

1. `npm run start:dev` with the code below and kill a process like before (I tested killing+respawning a few workers)
2. Notice on BullBoard that some jobs are still showing as active but will never complete. This is the most likely explanation for how the "stuck active" jobs happen (i.e., the Node process that was working on them gets killed and they never get retried by another process or cleaned up after their lock expires)
3. Restarting the server and/or killing more processes no longer causes any issues. I can consistently reproduce the "missing lock for job" error again, however, if I set either `SHOULD_TRIGGER_ERROR_PATH1` or `SHOULD_TRIGGER_ERROR_PATH2` to true.

One other thing: with this example, the "stuck active" jobs are cleared in obliterate. For some reason, however, this is not the case in my actual full repo. For anyone's future reference, this code below is the only thing that seems to remove those active jobs:
```ts
async function deleteOldActiveJobs(queue: Queue, queueLogger: Logger) {
  const oldActiveJobs = await queue.getJobs(['active'])
  queueLogger.info(
    `Removing ${oldActiveJobs.length} leftover active jobs from ${queue.name}`
  )
  return Promise.allSettled(oldActiveJobs.map((job) => job.remove()))
}
```

Here's the full minimal Bull+Express+BullBoard code that doesn't have any issues as far as I can tell (also updated [the standalone repo](https://github.com/theoilie/cluster-bull)):
```ts
import { createBullBoard } from '@bull-board/api'
import { BullAdapter } from '@bull-board/api/bullAdapter'
import { ExpressAdapter } from '@bull-board/express'
import { Queue, Worker } from 'bullmq'
import cluster from 'cluster'
import express from 'express'

const REDIS_HOST = '127.0.0.1'
const REDIS_PORT = 6379
const PORT = 5005
const CLUSTER_ENABLED = true
const NUM_CLUSTER_WORKERS = 2
const BULL_CONCURRENCY_PER_PROCESS = 5

/**
 * Path 1 to trigger the error - without this initComplete flow, "missing lock for job" will happen if you:
 * 1. Start the app once, wait a minute, and kill a worker
 * 2. Restart the app
 * 
 * This is possibly caused by the second worker initting and processing a job that
 * the first worker is still trying to remove.
 */
const SHOULD_TRIGGER_ERROR_PATH1 = false

/**
 * Path 2 to trigger the error - if every worker calls `queue.obliterate({ force: true })`:
 * 1. Start the app, wait a minute, and kill a worker.
 * 2. The "missing lock for job" error should be logged. If not, repeat a couple of times.
 * 
 * This is possibly caused by one worker trying work on a job while another worker
 * tries to obliterate that job.
 */
const SHOULD_TRIGGER_ERROR_PATH2 = false

const log = (msg: any) => {
  const worker = cluster.worker?.id ?? 'primary'
  console.log(`[worker ${worker}] ${msg}`)
}

const getRandomNum = (min: number, max: number) => {
  return Math.floor(Math.random() * (max - min + 1)) + min
}

const addJobsToQueue = async (queue: Queue) => {
  while (true) {
    await queue.add('test job', { randomNumber: getRandomNum(0, 100) })
    await timeout(getRandomNum(1000, 10_000))
  }
}

const deleteOldActiveJobs = async (queue: Queue) => {
  const oldActiveJobs = await queue.getJobs(['active'])
  log(
    `Removing ${oldActiveJobs.length} leftover active jobs from ${queue.name}`
  )
  return Promise.allSettled(oldActiveJobs.map((job) => job.remove()))
}

const timeout = (ms: number) => {
  return new Promise((resolve) => setTimeout(resolve, ms))
}

// The primary process performs one-time validation and spawns worker processes that each run the Express app
const startAppForPrimary = async () => {
  log(`Primary process with pid=${process.pid} is running...`)
  const errorExpected = SHOULD_TRIGGER_ERROR_PATH1 || SHOULD_TRIGGER_ERROR_PATH2
  if (errorExpected) {
    log('Expect to see an error if you kill a process and restarting (hot reload).')
  } else {
    log('There should NOT be any errors after killing a process and restarting (hot reload)/')
  }

  // Spawn cluster workers (child processes of the primary)
  log(`Spawning ${NUM_CLUSTER_WORKERS} processes to run the Express app. Each will have its own queue worker to process ${BULL_CONCURRENCY_PER_PROCESS} Bull jobs concurrently...`)
  
  if (SHOULD_TRIGGER_ERROR_PATH1) {
    for (let i = 0; i < NUM_CLUSTER_WORKERS; i++) {
      cluster.fork()
    }
  } else {
    // Wait for the first worker to perform one-time cleanup logic before spawning other workers
    const firstWorker = cluster.fork()
    firstWorker.on('message', (msg) => {
      if (msg?.cmd === 'initComplete') {
        for (let i = 0; i < NUM_CLUSTER_WORKERS - 1; i++) {
          cluster.fork()
        }
      }
    })
  }

  // Respawn workers when they die
  cluster.on('exit', (worker, code, signal) => {
    log(
      `Worker process with pid=${worker.process.pid} died because ${
        signal || code
      }. Respawning...`
    )
    cluster.fork()
  })
}

// Workers don't share memory - each is its own process running its own Express app and Redis connections for Bull queues
const startAppForWorker = async () => {
  log(`Worker process with pid=${process.pid} and worker is running`)
  await startApp()
}

const startAppWithoutCluster = async () => {
  log(`Starting app with cluster mode disabled...`)
  await startApp()
}

const startApp = async () => {
  // Create Express server
  const app = express()
  app.listen(PORT)

  // Make a queue with a worker
  const queueName = 'test-queue'
  const connection = {
    host: REDIS_HOST,
    port: REDIS_PORT
  } as any
  const queue = new Queue(queueName, { connection })
  if (SHOULD_TRIGGER_ERROR_PATH2) {
    await queue.obliterate({ force: true })
  } else if (cluster.worker?.id === 1) {
    await queue.obliterate({ force: true })
    await deleteOldActiveJobs(queue)
  }
  new Worker(
    queueName,
    async (job) => {
      await timeout(getRandomNum(1000, 10_000))
      return { randomNumber: job.data.randomNumber }
    },
    {
      connection,
      concurrency: BULL_CONCURRENCY_PER_PROCESS
    }
  )

  // Setup `/dashboard` endpoint to view queue info
  const serverAdapter = new ExpressAdapter()
  createBullBoard({
    queues: [new BullAdapter(queue)],
    serverAdapter
  })
  serverAdapter.setBasePath('/dashboard')
  app.use('/dashboard', serverAdapter.getRouter())

   if (cluster.worker?.id === 1 && process.send) {
    process.send({ cmd: 'initComplete' })
  }

  await addJobsToQueue(queue)
}

if (!CLUSTER_ENABLED) startAppWithoutCluster()
else if (cluster.isMaster) startAppForPrimary()
else if (cluster.isWorker) startAppForWorker()
else throw new Error("Can't determine if process is primary or worker in cluster")

```
