### ISSUE TITLE
Connection failure: Google redis, client command

### ISSUE THREAD

**Issue by Shannanigans** [taskforcesh/bullmq#1585]
`3.2.0` -> functions on google cloud managed redis.
`3.3.3` -> Breaks on google cloud managed redis.

Error log:
```
ReplyError: ERR unknown command `client`, with args beginning with: `SETNAME`, `bull:dHJhbnNhY3Rpb24=`, at parseError (/usr/src/app/node_modules/redis-parser/lib/parser.js:179:12) at parseType (/usr/src/app/node_modules/redis-parser/lib/parser.js:302:14) {
```

It would appear that the update to bullmq `3.3.3` makes use of code in the redis-parser lib via ioredis which uses the forbidden `client` command which fails on google managed redis instances.

https://cloud.google.com/memorystore/docs/redis/troubleshoot-issues

**Comment by roggervalf** [comment]
hi @Shannanigans, could you try version 3.3.4, since that version it should be fixed

**Comment by Shannanigans** [comment]
Hi @roggervalf, thank you for the fast feedback. We will try 3.3.4 and see if that resolves the issue.

**Comment by smonn** [comment]
Just saw this on our setup when using GCP's Redis memory store while running bullmq v3.15.1. We have the `reconnectOnError` setup for ioredis to catch various thrown errors. Not sure if the solution is to simply ignore the error or if this requires a fix in ioredis or bullmq.
