### ISSUE TITLE
Using IORedis keyPrefix feature causes "Missing lock" error

### ISSUE THREAD

**Issue by rysi3k** [taskforcesh/bullmq#1596]
Hello
IORedis has builtin feature to prefixing keys. When I try to reuse connection which uses that feature it cause error in bull.

Script:
```
import {Queue, Worker} from 'bullmq';
import IORedis from 'ioredis';

const connection = new IORedis.Cluster([{host: '10.0.6.161', port: 7379}], {
    // @ts-ignore becuase of wrong typings https://github.com/luin/ioredis/issues/1024 but works
    keyPrefix: '{abc}',
});

// Reuse the cluster instance
const myQueue = new Queue('myqueue', {connection});
new Worker('myqueue', async (job)=> {
    console.log('OK', job.id)
}, { connection });

myQueue.add('wall', {color: 'pink'});
```

Error:
```
Error: Missing lock for job 8. failed
    at Scripts.finishedErrors (/Users/user/projects/webdev/api-service/node_modules/.pnpm/bullmq@1.87.2/node_modules/bullmq/src/classes/scripts.ts:349:16)
    at Job.moveToFailed (/Users/user/projects/webdev/api-service/node_modules/.pnpm/bullmq@1.87.2/node_modules/bullmq/src/classes/job.ts:550:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async handleFailed (/Users/user/projects/webdev/api-service/node_modules/.pnpm/bullmq@1.87.2/node_modules/bullmq/src/classes/worker.ts:586:9)
    at async Worker.retryIfFailed (/Users/user/projects/webdev/api-service/node_modules/.pnpm/bullmq@1.87.2/node_modules/bullmq/src/classes/worker.ts:730:16)
    at async Worker.run (/Users/user/projects/webdev/api-service/node_modules/.pnpm/bullmq@1.87.2/node_modules/bullmq/src/classes/worker.ts:350:34)
```

It will be nice to handle that case as well.

Regards

**Comment by manast** [comment]
In this case, we need to throw an exception when instantiating a queue with a connection that uses this option since the option is not compatible with BullMQ.
