### ISSUE TITLE
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [WriteStream]. Use emitter.setMaxListeners()  to increase limit

### ISSUE THREAD

**Issue by nhayhoc** [taskforcesh/bullmq#1747]
### Version

v18.4.2

### Platform

NodeJS

### What happened?

Bull version: bullmq@3.10.1
```
(node:12088) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [WriteStream]. Use emitter.setMaxListeners() 
to increase limit
    at _addListener (node:events:587:17)
    at WriteStream.prependListener (node:events:619:14)
    at prependListener (node:internal/streams/legacy:100:20)
    at Socket.Readable.pipe (node:internal/streams/readable:791:3)
    at ChildPool.retain (D:\WorkspaceWin\riot-api-backend-global\node_modules\bullmq\src\classes\child-pool.ts:121:18)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Worker.process (D:\WorkspaceWin\riot-api-backend-global\node_modules\bullmq\src\classes\sandbox.ts:11:19)
    at Worker.processJob (D:\WorkspaceWin\riot-api-backend-global\node_modules\bullmq\src\classes\worker.ts:655:22)
    at Worker.retryIfFailed (D:\WorkspaceWin\riot-api-backend-global\node_modules\bullmq\src\classes\worker.ts:846:16)
```

My code: 
```
@Injectable()
export class ServerApiQueue {
  public readonly tftQueue: Queue<ServerApiJobData>;
  public readonly tftQueueEvents: QueueEvents;
  public readonly tftWorker: Worker;


  constructor(private readonly configService: ConfigService) {
    console.log('new ServerApiQueue');
    const queueTft = this.CreateQueue(SERVER_API_TFT_QUEUE);
    this.tftQueue = queueTft.queue;
    this.tftQueueEvents = queueTft.queueEvent;
    this.tftWorker = queueTft.worker;

    
    setTimeout(() => {
      for (let i = 0; i < 100; i++) {
        this.tftQueue.add('', { url: i.toString(), api_key: i.toString() });
      }
    }, 5000);
  }
  private CreateQueue(name: string) {
   
    const connection = new IORedis(
      this.configService.get<number>('redis_port'),
      this.configService.get<string>('redis_host'),
      {
        maxRetriesPerRequest: null,
        enableReadyCheck: false,
      },
    );
    const isDev = this.configService.get<boolean>('is_dev');
    const queue = new Queue<ServerApiJobData>(name, {
      connection: connection,
      defaultJobOptions: {
        removeOnComplete: { count: 1000 },
        removeOnFail: { count: 1000 },
      },
    });
    const queueEvent = new QueueEvents(name, {
      connection: connection,
    });
    queueEvent.setMaxListeners(100);
    queue.setMaxListeners(100);
    const worker = new Worker(name, path.join(__dirname, 'processor.js'), {
      connection: connection,
      limiter: {
        max: isDev ? 20 : 50,
        duration: 1000,
      },

      concurrency: isDev ? 10 : 50,
    });
    return { queue, queueEvent, worker };
  }
}

```
I see a warning from the WriteStream function, will it cause any serious errors in the future? Is this a bug from my code or a problem from somewhere else? How to solve?
Thanks for taking the time!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manast** [comment]
Please, search on older issues as this has been already explained at length many times.
