### ISSUE TITLE
Connection test failures due to UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by maxogden** [taskforcesh/bullmq#192]
Hi, I hope this bug report is useful. I was running `yarn test` locally  (Redis 6.0.0, Node v12, commit https://github.com/taskforcesh/bullmq/commit/8ee4d685dec7a92f050d752f29375b5f58cc6c72) and got 2 test failures:

```
  connection
    1) should recover from a connection loss
(node:340633) UnhandledPromiseRejectionWarning: Error: ECONNRESET
    at Worker.<anonymous> (/home/max/exodus/bullmq/src/test/test_connection.ts:83:35)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:340633) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 11)
    2) should handle jobs added before and after a redis disconnect
    ✓ should fail if redis connection fails
(node:340633) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:1234
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1128:14)
(node:340633) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 12)
(node:340633) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:1234
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1128:14)
(node:340633) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 13)
(node:340633) UnhandledPromiseRejectionWarning: Error: Connection is closed.
    at Redis.sendCommand (/home/max/exodus/bullmq/node_modules/ioredis/built/redis/index.js:572:24)
    at Redis.hset (/home/max/exodus/bullmq/node_modules/ioredis/built/commander.js:124:21)
    at /home/max/exodus/bullmq/src/classes/queue.ts:26:14
(node:340633) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 14)

...

 170 passing (49s)
  4 pending
  2 failing

  1) connection
       should recover from a connection loss:
     Error: ECONNRESET
      at Context.<anonymous> (src/test/test_connection.ts:46:32)                                                                                                            
      at runMicrotasks (<anonymous>)                                                                                                                                        
      at processTicksAndRejections (internal/process/task_queues.js:93:5)                                                                                                   

  2) connection
       should handle jobs added before and after a redis disconnect:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/max/exodus/bullmq/src/test/test_connection.ts)                                                                                                                                                         
      at listOnTimeout (internal/timers.js:531:17)                                                                                                                          
      at processTimers (internal/timers.js:475:7)     
```

I was looking at `git blame` and noticed this https://github.com/taskforcesh/bullmq/commit/a15b1a1824c6863ecf3e5132e22924fc3ff161f6, reverted it, and all the tests started passing for me

**Comment by maxogden** [comment]
Also I just noticed that CI is broken on master as well, but in the readme the CI badge links to the old repo still so it shows it as passing

**Comment by janhartigan** [comment]
Just chiming in that this bug is coming up for me as well.

**Comment by manast** [comment]
Yes, I have seen this too. Not sure in which PR this was introduced. Travis was half-broken and I think I mistakingly merged a broken version. Will look into it ASAP.

**Comment by janhartigan** [comment]
@manast any updates on this? Holding off on updating to the latest version due to the bug persisting. Let me know if you need someone to dig into this further.

**Comment by manast** [comment]
This is fixed since a couple of releases back. Will close now.
