### ISSUE TITLE
[Bug]: ReplyError: READONLY You can't write against a read only replica.

### ISSUE THREAD

**Issue by renato-oficial** [taskforcesh/bullmq#1928]
### Version

v3.10.3

### Platform

NodeJS

### What happened?

ReplyError: READONLY You can't write against a read only replica.
    at parseError (/root/xtreamui-stable-v1/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/root/xtreamui-stable-v1/node_modules/redis-parser/lib/parser.js:302:14) {
  command: {
    name: 'hset',
    args: [ 'bull:Paint:meta', 'opts.maxLenEvents', '10000' ]
  }
}

### How to reproduce.

I have my application on a vps and when I try to reproduce the simple example from the documentation this error happens

const { Queue } = reuquire('bullmq')
const queue = new Queue('Paint');

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luddd3** [comment]
This is ioredis way of telling you that the Redis instance you are connecting to is in read only mode.
