### ISSUE TITLE
[Bug]:  Missing lock for job MoveToDelayed

### ISSUE THREAD

**Issue by LitHaxor** [taskforcesh/bullmq#2094]
### Version

4.6.0

### Platform

NodeJS

### What happened?

```ts
import { Worker, Job } from "bullmq";
import { redisConfig } from "../config";


const worker = new Worker(
  'main_worker',
  async (job: Job) => {
    await somethingProcesssing();
    
    job.moveToDelayed(Date.now() + 10 * 1000);
  },
  {
    autorun: false,
    connection: {
      ...redisConfig,
    },
  }
);

worker.run();


```
Why I am getting this error?

```bash
Error: Missing lock for job awQWbcmgj6. moveToDelayed
    at Scripts.finishedErrors (/Users/lithasan/Desktop/Munchies/AutoRiderAssign/node_modules/bullmq/src/classes/scripts.ts:338:16)
    at Scripts.moveToDelayed (/Users/lithasan/Desktop/Munchies/AutoRiderAssign/node_modules/bullmq/src/classes/scripts.ts:658:18)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### How to reproduce.

import { Worker, Job } from "bullmq";
import { redisConfig } from "../config";

const worker = new Worker(
  'main_worker',
  async (job: Job) => {
    await somethingProcesssing();
    
    job.moveToDelayed(Date.now() + 10 * 1000, token);
  },
  {
    autorun: false,
    connection: {
      ...redisConfig,
    },
  }
);

worker.run();

### Relevant log output

```shell
Error: Missing lock for job awQWbcmgj6. moveToDelayed
    at Scripts.finishedErrors (/Users/lithasan/Desktop/Munchies/AutoRiderAssign/node_modules/bullmq/src/classes/scripts.ts:338:16)
    at Scripts.moveToDelayed (/Users/lithasan/Desktop/Munchies/AutoRiderAssign/node_modules/bullmq/src/classes/scripts.ts:658:18)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by roggervalf** [comment]
Hi @LitHaxor, looks like you're missing DelayedError https://docs.bullmq.io/patterns/process-step-jobs#delaying

**Comment by LitHaxor** [comment]
> Hi @LitHaxor, looks like you're missing DelayedError https://docs.bullmq.io/patterns/process-step-jobs#delaying

So I want to forcely move a job to delayed state! 

How i can achieve it?

**Comment by LitHaxor** [comment]
> Hi @LitHaxor, looks like you're missing DelayedError https://docs.bullmq.io/patterns/process-step-jobs#delaying

That resolves my problem
