### ISSUE TITLE
[Bug]: returnvalue not JSON.stringified in python job

### ISSUE THREAD

**Issue by klaemo** [taskforcesh/bullmq#2196]
### Version

1.13.2

### Platform

Python

### What happened?

Writing a processor function that returns a plain string
```python
async def process(job):
    return 'foo'
```
and listening to the queue events in **JavaScript** will throw an error when JavaScript tries to JSON.parse the return value:

```
SyntaxError: Unexpected token 'o', "foo" is not valid JSON
    at JSON.parse (<anonymous>)
    at QueueEvents.consumeEvents (/Users/clemens/Projects/bullmq-example/producer/node_modules/bullmq/dist/cjs/classes/queue-events.js:92:53)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async QueueEvents.run (/Users/clemens/Projects/bullmq-example/producer/node_modules/bullmq/dist/cjs/classes/queue-events.js:60:17)
```

Similarily, returning an array will also fail
```python
async def process(job):
    return ['foo']
```
```
Error processing job Invalid input of type: 'list'. Convert to a bytes, string, int or float first.
```

I think the python code should probably use `json.dumps(result)` here https://github.com/taskforcesh/bullmq/blob/3b6719379cbec5beb1b7dfb5f06d46cbbf74010f/python/bullmq/worker.py#L167

### How to reproduce.

```python
from bullmq import Worker

async def process(job):
    return 'foo'

async def main():
    # Feel free to remove the connection parameter, if your redis runs on localhost
    worker = Worker("myQueue", process, {"connection": "localhost"})

    # This while loop is just for the sake of this example
    # you won't need it in practice.
    while True: # Add some breaking conditions here
        await asyncio.sleep(1)

    # When no need to process more jobs we should close the worker
    await worker.close()

if __name__ == "__main__":
    asyncio.run(main())
```

```js
const events = new QueueEvents("myQueue");

events.on("completed", (evt) => {
  console.log(evt);
});
```

### Relevant log output

```shell
SyntaxError: Unexpected token 'o', "foo" is not valid JSON
    at JSON.parse (<anonymous>)
    at QueueEvents.consumeEvents (/Users/clemens/Projects/bullmq-example/producer/node_modules/bullmq/dist/cjs/classes/queue-events.js:92:53)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async QueueEvents.run (/Users/clemens/Projects/bullmq-example/producer/node_modules/bullmq/dist/cjs/classes/queue-events.js:60:17)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by klaemo** [comment]
Wow, thank you so much for the quick fix! 🤩 Can confirm that it works as intended now.
