### ISSUE TITLE
[Bug]: MoveToActive is called after force closing worker

### ISSUE THREAD

**Issue by lukas-becker0** [taskforcesh/bullmq#2212]
### Version

v4.12.0

### Platform

NodeJS

### What happened?

Force closing the worker (`await worker.close(true)`) results in an unexpected error in the error event listener of the worker after the worker was successfully closed.

Is this expected behavior ? 

Without the force flag the issue does not appear.

(The example code is a simplified version and the reason we create a new queue+worker with each interval is to mimic our requirement to create and cleanup new queues+workers on the fly during runtime). 

### How to reproduce.

Run the following code:

```typescript
import { Queue, Worker } from 'bullmq';
import * as console from 'console';
import { randomUUID } from 'crypto';
import { setTimeout } from 'timers/promises';

function constructTemporaryQueueAndWorker() {
	const queueName = `test-worker-cleanup-${randomUUID()}`;

	const queue = new Queue(queueName, {
		connection: {
			host: 'localhost',
			port: 6379,
		},
	}).on('error', (error) => {
		console.error(error);
	});

	const worker = new Worker(
		queueName,
		async (job) => {
			console.log(`Processing job: ${job.id}`);
			return 'OK';
		},
		{
			autorun: false,
			connection: {
				host: 'localhost',
				port: 6379,
			},
		},
	);

	worker
		.on('error', (error) => {
			console.error(error);
		})
		.on('failed', (job, error) => {
			console.warn(`Job ${job.id} failed with error: ${error.message}`);
		})
		.on('completed', (job, returnValue) => {
			console.log(`Job ${job.id} completed with result: ${returnValue}`);
		})
		.on('closing', () => {
			console.debug(`Closing worker ...`);
		})
		.on('closed', () => {
			console.debug(`Closed worker!`);
		})
		.on('ioredis:close', () => {
			console.debug(`Redis client closed for worker!`);
		});

	return { queue, worker };
}

async function runTempQueue() {
	const { queue, worker } = constructTemporaryQueueAndWorker();

	try {
		worker.run().catch((error) => {
			console.error(error);
		});

		await queue.add('test-job', {});

		await setTimeout(200);

		await queue.close();
		await worker.close(true);
	} finally {
		setTimeout(500)
			.then(() => {
				queue && queue.removeAllListeners();
				worker && worker.removeAllListeners();
			})
			.catch((error) => {
				console.error(error);
			});
	}
}

async function main() {
	const interval = setInterval(() => {
		runTempQueue()
			.then(() => {
				console.log(`Completed run ${new Date()}`);
			})
			.catch((error) => {
				console.error(error);
			});
	}, 600);

	process.on('SIGTERM', () => {
		clearInterval(interval);
	});
}

main();

```

### Relevant log output

```shell
Processing job: 1
Job 1 completed with result: OK
Closing worker ...
Closed worker!
Completed run Wed Oct 04 2023 11:33:32 GMT+0200 (Central European Summer Time)
Error: Connection is closed.
    at EventEmitter.sendCommand (/Users/lukas.becker/test-project/node_modules/ioredis/built/Redis.js:332:28)
    at Script.execute (/Users/lukas.becker/test-project/node_modules/ioredis/built/Script.js:59:26)
    at EventEmitter.moveToActive (/Users/lukas.becker/test-project/node_modules/ioredis/built/utils/Commander.js:111:27)
    at Scripts.moveToActive (/Users/lukas.becker/test-project/node_modules/bullmq/src/classes/scripts.ts:864:40)




Processing job: 1
Job 1 completed with result: OK
Closing worker ...
Closed worker!
Completed run Wed Oct 04 2023 12:20:37 GMT+0200 (Central European Summer Time)
Error: Connection is closed.
    at close (/Users/lukas.becker/test-project/node_modules/ioredis/built/redis/event_handler.js:189:25)
    at Socket.<anonymous> (/Users/lukas.becker/test-project/node_modules/ioredis/built/redis/event_handler.js:156:20)
    at Object.onceWrapper (node:events:629:26)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:489:12)
    at TCP.<anonymous> (node:net:337:12)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lukas-becker0** [comment]
Could someone please tell me what I did wrong regarding this ticket ? 
I do not understand why I'm not get a response.

**Comment by lukas-becker0** [comment]
Alright, thanks for clarifying this.
