### ISSUE TITLE
Failed Job - Missing lock for job and Maximum call stack size exceeded

### ISSUE THREAD

**Issue by ingeniousambivert** [taskforcesh/bullmq#2230]
### Version

4.12.3

### Platform

NodeJS

### What happened?

This behaviour happened when I migrated from version 1.54.0 to 4.12.3. And I just removed the QueueScheduler from the architecture. Everything else is exactly the same. 

### How to reproduce.

```
import { Worker, Queue } from "bullmq";

async function bootBullMQ() {
	console.log("Started BULL MQ");

	const sampleName = "TEST_BULL_MQ";
	const connection = {
		host: "localhost",
		port: 6379,
	};

	const worker = new Worker(sampleName, (_) => _, {
		connection,
	});

	const queue = new Queue(sampleName, {
		connection,
		defaultJobOptions: {
			attempts: 3,
			backoff: {
				type: "exponential",
				delay: 1000,
			},
		},
	});

	await queue.add(
		sampleName,
		{ foo: "bar" },
		{
			repeat: {
				pattern: "* * * * *",
			},
		}
	);

	worker.on("completed", (job) => {
		console.log(`${job.id} completed`);
	});

	worker.on("failed", (job, err) => {
		console.log(`${job.id} failed - ${err.message}`);
		console.log(err);
	});

	worker.on("error", (err) => {
		console.log(`worker error - ${err.message}`);
		console.log(err);
	});
}

export { bootBullMQ };
```

### Relevant log output

```shell
worker error - Missing lock for job repeat:684ce654ac0d56773f3ab5db3256ed88:1697223960000. delayed
208 |     finishedErrors(code, jobId, command, state) {
209 |         switch (code) {
210 |             case enums_1.ErrorCode.JobNotExist:
211 |                 return new Error(`Missing key for job ${jobId}. ${command}`);
212 |             case enums_1.ErrorCode.JobLockNotExist:
213 |                 return new Error(`Missing lock for job ${jobId}. ${command}`);
                           ^
error: Missing lock for job repeat:684ce654ac0d56773f3ab5db3256ed88:1697223960000. delayed
      at finishedErrors (/Users/user/Documents/Projects/sample/node_modules/bullmq/dist/cjs/classes/scripts.js:213:23)
      at /Users/user/Documents/Projects/sample/node_modules/bullmq/dist/cjs/classes/job.js:427:18
      at processTicksAndRejections (:1:2602)

repeat:684ce654ac0d56773f3ab5db3256ed88:1697224020000 failed - Maximum call stack size exceeded.
 9 | exports.errorObject = { value: null };
10 | function tryCatch(fn, ctx, args) {
11 |     try {
12 |         return fn.apply(ctx, args);
13 |     }
14 |     catch (e) {
        ^
RangeError: Maximum call stack size exceeded.
      at /Users/user/Documents/Projects/sample/node_modules/bullmq/dist/cjs/utils.js:14:4
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manast** [comment]
What about the missing "async" here:
```ts
	const worker = new Worker(sampleName, async (_) => _, {
		connection,
	});
```

**Comment by manast** [comment]
Ok, the async is not needed anymore. The error is produced when you return ```_``` as the result of the job, if you read the callstack you can see the error perfectly:
```ts
repeat:684ce654ac0d56773f3ab5db3256ed88:1697276280000 failed - Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at Job.toJSON (/Users/manuelastudillo/Dev/taskforce/bullmq/dist/cjs/classes/job.js:226:11)
    at JSON.stringify (<anonymous>)
    at tryCatch (/Users/manuelastudillo/Dev/taskforce/bullmq/dist/cjs/utils.js:12:19)
    at Job.moveToCompleted (/Users/manuelastudillo/Dev/taskforce/bullmq/dist/cjs/classes/job.js:358:61)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async handleCompleted (/Users/manuelastudillo/Dev/taskforce/bullmq/dist/cjs/classes/worker.js:316:35)
    at async Worker.processJob (/Users/manuelastudillo/Dev/taskforce/bullmq/dist/cjs/classes/worker.js:351:20)
    at async Worker.retryIfFailed (/Users/manuelastudillo/Dev/taskforce/bullmq/dist/cjs/classes/worker.js:535:24)
```

Do not return the job and it will work:
```ts
const worker = new Worker(
    sampleName,
    (_job) => {
      console.log("BULL MQ Works!");
    },
    {
      connection,
    }
  );
```
