### ISSUE TITLE
[Bug]: ReplyError: ERR user_script:201: Cannot serialise number: must not be NaN or Inf script: 6c25fa0b8bf82ab072e19d624f145540fe35ec57, on @user_script:201.

### ISSUE THREAD

**Issue by NITHISH-1609** [taskforcesh/bullmq#2234]
### Version

v4.8.0

### Platform

NodeJS

### What happened?

In my logs, I can see an error got occured and not sure why and how to debug this!
`ReplyError: ERR user_script:201: Cannot serialise number: must not be NaN or Inf script: 6c25fa0b8bf82ab072e19d624f145540fe35ec57, on @user_script:201`

<img width="1182" alt="Screenshot 2023-10-16 at 23 50 01" src="https://github.com/taskforcesh/bullmq/assets/61798905/34fc178d-5123-43bc-aa07-3ddc35fb8c26">

I don't understand the error and it cause. But I can see`reconnectOnError` function got triggered. Here is my code snippet

```
export const redisConnectionOption = {
  port: +process.env.REDIS_PORT!,
  host: process.env.REDIS_HOST,
  reconnectOnError: () => {
    console.log("Redis connection failed... Retrying....");
    return true;
  },
};

```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manast** [comment]
Can you provide the rest of the log? specifically where we can see the arguments sent to the LUA script, seems like there is some option that has an invalid value. Are you using typescript? Also, try with the latest version as it may throw a better exception if you are passing invalid values.

**Comment by NITHISH-1609** [comment]
Yes, I'm using typescript!

Here is the complete log, hope it helps!:
```
Uncaught Exception: ReplyError: ERR user_script:201: Cannot serialise number: must not be NaN or Inf script: 6c25fa0b8bf82ab072e19d624f145540fe35ec57, on @user_script:201.
 at parseError (/var/app/current/node_modules/redis-parser/lib/parser.js:179:12)
 at parseType (/var/app/current/node_modules/redis-parser/lib/parser.js:302:14) {
 command: {
 name: 'eval',
 args: [
 '--[[\n' +
 '  Adds a job to the queue by doing the following:\n' +
 '    - Increases the job counter if needed.\n' +
 '    - Creates a new job key with the job data.\n' +
 '    - if delayed:\n' +
 '      - computes timestamp.\n' +
 '      - adds to delayed zset.\n' +
 "      - Emits a global event 'delayed' if the job is delayed.\n" +
 '    - if not delayed\n' +
 '      - Adds the jobId to the wait/paused list in one of three ways:\n' +
 '         - LIFO\n' +
 '         - FIFO\n' +
 '         - prioritized.\n' +
 '      - Adds the job to the "added" list so that workers gets notified.\n' +
 '    Input:\n' +
 "      KEYS[1] 'wait',\n" +
 "      KEYS[2] 'paused'\n" +
 "      KEYS[3] 'meta'\n" +
 "      KEYS[4] 'id'\n" +
 "      KEYS[5] 'delayed'\n" +
 "      KEYS[6] 'prioritized'\n" +
 "      KEYS[7] 'completed'\n" +
 '      KEYS[8] events stream key\n' +
 "      KEYS[9] 'pc' priority counter\n" +
 '      ARGV[1] msgpacked arguments array\n' +
 '            [1]  key prefix,\n' +
 '            [2]  custom id (will not generate one automatically)\n' +
 '            [3]  name\n' +
 '            [4]  timestamp\n' +
 '            [5]  parentKey?\n' +
 '            [6]  waitChildrenKey key.\n' +
 '            [7]  parent dependencies key.\n' +
 '            [8]  parent? {id, queueKey}\n' +
 '            [9]  repeat job key\n' +
 '      ARGV[2] Json stringified job data\n' +
 '      ARGV[3] msgpacked options\n' +
 '      Output:\n' +
 '        jobId  - OK\n' +
 '        -5     - Missing parent key\n' +
 ']]\n' +
 'local jobId\n' +
 'local jobIdKey\n' +
 'local rcall = redis.call\n' +
 'local args = cmsgpack.unpack(ARGV[1])\n' +
 'local data = ARGV[2]\n' +
 'local opts = cmsgpack.unpack(ARGV[3])\n' +
 'local parentKey = args[5]\n' +
 'local repeatJobKey = args[9]\n' +
 'local parent = args[8]\n' +
 'local parentData\n' +
 '-- Includes\n' +
 '--[[\n' +
 '  Add delay marker if needed.\n' +
 ']]\n' +
 '-- Includes\n' +
 '--[[\n' +
 '  Function to return the next delayed job timestamp.\n' +
 ']] \n' +
 'local function getNextDelayedTimestamp(delayedKey)\n' +
 '  local result = rcall("ZRANGE", delayedKey, 0, 0, "WITHSCORES")\n' +
 '  if #result then\n' +
 '    local nextTimestamp = tonumber(result[2])\n' +
 '    if (nextTimestamp ~= nil) then \n' +
 '      nextTimestamp = nextTimestamp / 0x1000\n' +
 '    end\n' +
 '    return nextTimestamp\n' +
 '  end\n' +
 'end\n' +
 'local function addDelayMarkerIfNeeded(targetKey, delayedKey)\n' +
 '  if rcall("LLEN", targetKey) == 0 then\n' +
 '    local nextTimestamp = getNextDelayedTimestamp(delayedKey)\n' +
 '    if nextTimestamp ~= nil then\n' +
 '      rcall("LPUSH", targetKey, "0:" .. nextTimestamp)\n' +
 '    end\n' +
 '  end\n' +
 'end\n' +
 '--[[\n' +
 '  Function to add job considering priority.\n' +
 ']]\n' +
 '-- Includes\n' +
 '--[[\n' +
 '  Function priority marker to wait if needed\n' +
 '  in order to wake up our workers and to respect priority\n' +
 '  order as much as possible\n' +
 ']]\n' +
 'local function addPriorityMarkerIfNeeded(waitKey)\n' +
 '  local waitLen = rcall("LLEN", waitKey)\n' +
 '  if waitLen == 0 then\n' +
 '    rcall("LPUSH", waitKey, "0:0")\n' +
 '  end\n' +
 'end\n' +
 'local function addJobWithPriority(waitKey, prioritizedKey, priority, paused, jobId, priorityCounterKey)\n' +
 '  local prioCounter = rcall("INCR", priorityCounterKey)\n' +
 '  local score = priority * 0x100000000 + bit.band(prioCounter, 0xffffffffffff)\n' +
 '  rcall("ZADD", prioritizedKey, score, jobId)\n' +
 '  if not paused then\n' +
 '    addPriorityMarkerIfNeeded(waitKey)\n' +
 '  end\n' +
 'end\n' +
 '--[[\n' +
 '  Function to check for the meta.paused key to decide if we are paused or not\n' +
 '  (since an empty list and !EXISTS are not really the same).\n' +
 ']]\n' +
 'local function getTargetQueueList(queueMetaKey, waitKey, pausedKey)\n' +
 '  if rcall("HEXISTS", queueMetaKey, "paused") ~= 1 then\n' +
 '    return waitKey, false\n' +
 '  else\n' +
 '    return pausedKey, true\n' +
 '  end\n' +
 'end\n' +
 '--[[\n' +
 '  Function to trim events, default 10000.\n' +
 ']]\n' +
 'local function trimEvents(metaKey, eventStreamKey)\n' +
 '  local maxEvents = rcall("HGET", metaKey, "opts.maxLenEvents")\n' +
 '  if maxEvents ~= false then\n' +
 '    rcall("XTRIM", eventStreamKey, "MAXLEN", "~", maxEvents)\n' +
 '  else\n' +
 '    rcall("XTRIM", eventStreamKey, "MAXLEN", "~", 10000)\n' +
 '  end\n' +
 'end\n' +
 '--[[\n' +
 '  Validate and move or add dependencies to parent.\n' +
 ']]\n' +
 '-- Includes\n' +
 '--[[\n' +
 '  Validate and move parent to active if needed.\n' +
 ']]\n' +
 '-- Includes\n' +
 'local function moveParentToWaitIfNeeded(parentQueueKey, parentDependenciesKey, parentKey, parentId, timestamp)\n' +
 '  local isParentActive = rcall("ZSCORE", parentQueueKey .. ":waiting-children", parentId)\n' +
 '  if rcall("SCARD", parentDependenciesKey) == 0 and isParentActive then \n' +
 '    rcall("ZREM", parentQueueKey .. ":waiting-children", parentId)\n' +
 '    local parentWaitKey = parentQueueKey .. ":wait"\n' +
 '    local parentTarget, paused = getTargetQueueList(parentQueueKey .. ":meta", parentWaitKey,\n' +
 '      parentQueueKey .. ":paused")\n' +
 '    local jobAttributes = rcall("HMGET", parentKey, "priority", "delay")\n' +
 '    local priority = tonumber(jobAttributes[1]) or 0\n' +
 '    local delay = tonumber(jobAttributes[2]) or 0\n' +
 '    if delay > 0 then\n' +
 '      local delayedTimestamp = tonumber(timestamp) + delay \n' +
 '      local score = delayedTimestamp * 0x1000\n' +
 '      local parentDelayedKey = parentQueueKey .. ":delayed" \n' +
 '      rcall("ZADD", parentDelayedKey, score, parentId)\n' +
 '      rcall("XADD", parentQueueKey .. ":events", "*", "event", "delayed", "jobId", parentId,\n' +
 '        "delay", delayedTimestamp)\n' +
 '      addDelayMarkerIfNeeded(parentTarget, parentDelayedKey)\n' +
 '    else\n' +
 '      if priority == 0 then\n' +
 '        rcall("RPUSH", parentTarget, parentId)\n' +
 '      else\n' +
 '        addJobWithPriority(parentWaitKey, parentQueueKey .. ":prioritized", priority, paused,\n' +
 '          parentId, parentQueueKey .. ":pc")\n' +
 '      end\n' +
 '      rcall("XADD", parentQueueKey .. ":events", "*", "event", "waiting", "jobId", parentId,\n' +
 '        "prev", "waiting-children")\n' +
 '    end\n' +
 '  end\n' +
 'end\n' +
 'local function updateParentDepsIfNeeded(parentKey, parentQueueKey, parentDependenciesKey,\n' +
 '  parentId, jobIdKey, returnvalue, timestamp )\n' +
 '  local processedSet = parentKey .. ":processed"\n' +
 '  rcall("HSET", processedSet, jobIdKey, returnvalue)\n' +
 '  moveParentToWaitIfNeeded(parentQueueKey, parentDependenciesKey, parentKey, parentId, timestamp)\n' +
 'end\n' +
 'if parentKey ~= nil then\n' +
 '  if rcall("EXISTS", parentKey) ~= 1 then\n' +
 '    return -5\n' +
 '  end\n' +
 '  parentData = cjson.encode(parent)\n' +
 'end\n' +
 'local jobCounter = rcall("INCR", KEYS[4])\n' +
 '-- Trim events before emiting them to avoid trimming events emitted in this script\n' +
 'trimEvents(KEYS[3], KEYS[8])\n' +
 'local parentDependenciesKey = args[7]\n' +
 'local timestamp = args[4]\n' +
 'if args[2] == "" then\n' +
 '  jobId = jobCounter\n' +
 '  jobIdKey = args[1] .. jobId\n' +
 'else\n' +
 '  jobId = args[2]\n' +
 '  jobIdKey = args[1] .. jobId\n' +
 '  if rcall("EXISTS", jobIdKey) == 1 then\n' +
 '    if parentKey ~= nil then\n' +
 '      if rcall("ZSCORE", KEYS[7], jobId) ~= false then\n' +
 '        local returnvalue = rcall("HGET", jobIdKey, "returnvalue")\n' +
 "        updateParentDepsIfNeeded(parentKey, parent['queueKey'], parentDependenciesKey,\n" +
 "          parent['id'], jobIdKey, returnvalue, timestamp)\n" +
 '      else\n' +
 '        if parentDependenciesKey ~= nil then\n' +
 '          rcall("SADD", parentDependenciesKey, jobIdKey)\n' +
 '        end\n' +
 '      end\n' +
 '      rcall("HMSET", jobIdKey, "parentKey", parentKey, "parent", parentData)\n' +
 '    end\n' +
 '    rcall("XADD", KEYS[8], "*", "event", "duplicated", "jobId", jobId)\n' +
 '    return jobId .. "" -- convert to string\n' +
 '  end\n' +
 'end\n' +
 '-- Store the job.\n' +
 'local jsonOpts = cjson.encode(opts)\n' +
 "local delay = opts['delay'] or 0\n" +
 "local priority = opts['priority'] or 0\n" +
 'local optionalValues = {}\n' +
 'if parentKey ~= nil then\n' +
 '  table.insert(optionalValues, "parentKey")\n' +
 '  table.insert(optionalValues, parentKey)\n' +
 '  table.insert(optionalValues, "parent")\n' +
 '  table.insert(optionalValues, parentData)\n' +
 'end\n' +
 'if repeatJobKey ~= nil then\n' +
 '  table.insert(optionalValues, "rjk")\n' +
 '  table.insert(optionalValues, repeatJobKey)\n' +
 'end\n' +
 'rcall("HMSET", jobIdKey, "name", args[3], "data", ARGV[2], "opts", jsonOpts,\n' +
 '  "timestamp", timestamp, "delay", delay, "priority", priority, unpack(optionalValues))\n' +
 'rcall("XADD", KEYS[8], "*", "event", "added", "jobId", jobId, "name", args[3])\n' +
 '-- Check if job is delayed\n' +
 'local delayedTimestamp = (delay > 0 and (timestamp + delay)) or 0\n' +
 '-- Check if job is a parent, if so add to the parents set\n' +
 'local waitChildrenKey = args[6]\n' +
 'if waitChildrenKey ~= nil then\n' +
 '  rcall("ZADD", waitChildrenKey, timestamp, jobId)\n' +
 '  rcall("XADD", KEYS[8], "*", "event", "waiting-children", "jobId", jobId)\n' +
 'elseif (delayedTimestamp ~= 0) then\n' +
 '  local score = delayedTimestamp * 0x1000 + bit.band(jobCounter, 0xfff)\n' +
 '  rcall("ZADD", KEYS[5], score, jobId)\n' +
 '  rcall("XADD", KEYS[8], "*", "event", "delayed", "jobId", jobId, "delay",\n' +
 '        delayedTimestamp)\n' +
 '  -- If wait list is empty, and this delayed job is the next one to be processed,\n' +
 '  -- then we need to signal the workers by adding a dummy job (jobId 0:delay) to the wait list.\n' +
 '  local target = getTargetQueueList(KEYS[3], KEYS[1], KEYS[2])\n' +
 '  addDelayMarkerIfNeeded(target, KEYS[5])\n' +
 'else\n' +
 '  local target, paused = getTargetQueueList(KEYS[3], KEYS[1], KEYS[2])\n' +
 '  -- Standard or priority add\n' +
 '  if priority == 0 then\n' +
 '    -- LIFO or FIFO\n' +
 "    local pushCmd = opts['lifo'] and 'RPUSH' or 'LPUSH'\n" +
 '    rcall(pushCmd, target, jobId)\n' +
 '  else\n' +
 '    addJobWithPriority(KEYS[1], KEYS[6], priority, paused, jobId, KEYS[9])\n' +
 '  end\n' +
 '  -- Emit waiting event\n' +
 '  rcall("XADD", KEYS[8], "*", "event", "waiting", "jobId", jobId)\n' +
 'end\n' +
 '-- Check if this job is a child of another job, if so add it to the parents dependencies\n' +
 '-- TODO: Should not be possible to add a child job to a parent that is not in the "waiting-children" status.\n' +
 '-- fail in this case.\n' +
 'if parentDependenciesKey ~= nil then\n' +
 '  rcall("SADD", parentDependenciesKey, jobIdKey)\n' +
 'end\n' +
 'return jobId .. "" -- convert to string\n',
 '9',
 'bull:reminderQueue:wait',
 'bull:reminderQueue:paused',
 'bull:reminderQueue:meta',
 'bull:reminderQueue:id',
 'bull:reminderQueue:delayed',
 'bull:reminderQueue:prioritized',
 'bull:reminderQueue:completed',
 'bull:reminderQueue:events',
 'bull:reminderQueue:pc',
 <Buffer 99 b3 62 75 6c 6c 3a 72 65 6d 69 6e 64 65 72 51 75 65 75 65 3a a0 ad 72 65 6d 69 6e 64 65 72 51 75 65 75 65 cb 42 78 b2 5a 8e 45 c0 00 c0 c0 c0 c0 c0>,
{{QUEUE_DATA}} // I have the queue data here
```

**Comment by manast** [comment]
Are you using "delay" or "priority" ? seems like one of those options are NaN or Inf, typical error is to send a string instead of a number.

**Comment by manast** [comment]
Actually I am not sure which option could be, but the problem is in this line: 
```
 local jsonOpts = cjson.encode(opts)
```
So one option has an invalid number, if you examine the job's options you may be able to spot it.

**Comment by NITHISH-1609** [comment]
Thanks a lot for narrowing it down. I found the issue and fixed!
