### ISSUE TITLE
[Bug]: Error: Lock mismatch for job {id}. Cmd moveToFinished from active

### ISSUE THREAD

**Issue by AmreshSinha** [taskforcesh/bullmq#2354]
### Version

5.0.0

### Platform

NodeJS

### What happened?

I am testing out Bullmq for building a queue system for building docker image from GitHub URL using Nixpacks. It worked initially but after that, it's throwing the attached error message, every time I am adding an URL to the queue.

I am clueless here as I am not able to find any similar error online on StackOverflow or in any older issues. Any help would be appreciated.

Pardon me for the poor code. I am still a newbie >_>'

### How to reproduce.

Here is the repository: https://github.com/Paasify/nixpacks-queue-test

- Just open a codespace and `yarn && yarn dev`
- Do a POST req to `http://127.0.0.1:3000/add-to-build`
  - Body:
    ```json
    {
      "name": "sample-react-app",
      "url": "https://github.com/Paasify/Sample-React-App"
    }
    ```
- Remove the git repo before making another request: `rm -rf /tmp/repo*`

### Relevant log output

```shell
Processing job: 2
Error processing job: Error: Lock mismatch for job 2. Cmd moveToFinished from active
    at Scripts.finishedErrors (/workspaces/nixpacks-queue-test/node_modules/bullmq/src/classes/scripts.ts:424:16)
    at Scripts.moveToFinished (/workspaces/nixpacks-queue-test/node_modules/bullmq/src/classes/scripts.ts:396:18)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Job.moveToCompleted (/workspaces/nixpacks-queue-test/node_modules/bullmq/src/classes/job.ts:598:20)
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manast** [comment]
Why are you calling moveToFailed manually? you do not need to wrap your processor code in a try/catch either, this is handled automatically.

**Comment by manast** [comment]
You could just write it like this:
```ts
async (job: Job) => {
            console.log("Processing job:", job.id);

            const { id, name, url } = job.data;

            // Cloning the repository
            const repoDir = `/tmp/repo-${id}`
            const res = await cloneRepository(url, repoDir);
            console.log("Res", res);

            // Building the docker image using Nixpacks
            const result = await buildDockerImage(id, name, repoDir as string);

            console.log("Job completed:", result);

**Comment by geeksilva97** [comment]
Hey @manast . I've been facing a similar issue when using `moveToDelayed`. I provide the timestamp and it works, I mean it delays the job execution.

It generates errors, howerver

<img width="903" alt="image" src="https://github.com/taskforcesh/bullmq/assets/106174121/f2cfdc7b-2eb8-4730-8a04-4215aff03a65">
