### ISSUE TITLE
Job.moveToFailed fails in Cluster mode

### ISSUE THREAD

**Issue by joebowbeer** [taskforcesh/bullmq#257]
Stack trace:

```
Error: Sending custom commands in pipeline is not supported in Cluster mode.
at Pipeline.exec (node_modules/ioredis/built/pipeline.js:231:25)
at Pipeline.pipeline.exec (node_modules/ioredis/built/transaction.js:38:34)
at Job.moveToFailed (node_modules/bullmq/dist/classes/job.js:195:41)
```

Same issue as in Bull v3: https://github.com/OptimalBits/bull/issues/758

**Comment by joebowbeer** [comment]
I think the underlying ioredis [issue](https://github.com/luin/ioredis/issues/536) is [fixed](https://github.com/luin/ioredis/pull/1201) (but not yet released)

**Comment by roggervalf** [comment]
as there is a fix already merged we should be good to close this issue
