### ISSUE TITLE
[Bug]: Is it normal to get lots of "Command timed out" from bzpopmin?

### ISSUE THREAD

**Issue by Linksku** [taskforcesh/bullmq#2619]
### Version

v5.8.2

### Platform

NodeJS

### What happened?

I'm trying to migrate from Bull to BullMQ. I'm getting an issue where my repeatable jobs often don't run. I.e. even though it's past the delay job's run time, they're not running. It could be the same issue that other people reported, e.g. https://github.com/taskforcesh/bullmq/issues/2466

In order to debug this, I tried logging errors:

```
  worker.on('error', err => {
    console.log(err);
  });
```

This is logging this error roughly every second:

```
Command timed out
  at Worker.waitForJob (node_modules/bullmq/src/classes/worker.ts:641:40)
  at Worker._getNextJob (node_modules/bullmq/src/classes/worker.ts:547:27)
```

I've narrowed down the source of the error to the `bzpopmin` call in `waitForJob`. I tried increasing the timeout, but I'm still getting the error. Is this error expected to occur? If not, what might be some potential causes for this?

I think my code is fairly standard:

```
const queue = new Queue(queueName, {
    connection: {
      host: REDIS_HOST,
      port: REDIS_PORT,
      username: REDIS_USER,
      password: REDIS_PASS,
      maxRetriesPerRequest: null,
      enableOfflineQueue: false,
    },
    prefix: 'bull',
  });

  const worker = new Worker(
    queueName,
    processJob,
    {
      connection: {
        host: REDIS_HOST,
        port: REDIS_PORT,
        username: REDIS_USER,
        password: REDIS_PASS,
        maxRetriesPerRequest: null,
        enableOfflineQueue: true
      },
    },
  );

  await queue.add(
    jobName,
    null,
    {
      repeat: {
        every: 5 * 60 * 1000,
      },
      removeOnComplete: true,
      removeOnFail: true,
    },
  );
```

### Relevant log output

```shell
1719114352.234624 [0 172.20.0.1:49996] "bzpopmin" "bull:NotifsManager:marker" "10"
1719114352.836859 [0 172.20.0.1:50220] "bzpopmin" "bull:NotifsManager:marker" "10"
1719114353.037461 [0 172.20.0.1:60906] "bzpopmin" "bull:NotifsManager:marker" "10"
1719114353.137910 [0 172.20.0.1:32874] "bzpopmin" "bull:NotifsManager:marker" "10"
1719114355.481620 [0 127.0.0.1:51158] "AUTH" "(redacted)"
1719114360.951690 [0 172.20.0.1:50028] "eval" "--[[\n  Get counts per provided states\n    Input:\n      KEYS[1]    'prefix'\n      ARGV[1...] types\n]]\nlocal rcall = redis.call;\nlocal prefix = KEYS[1]\nlocal results = {}\nfor i = 1, #ARGV do\n  local stateKey = prefix .. ARGV[i]\n  if ARGV[i] == \"wait\" or ARGV[i] == \"paused\" then\n    -- Markers in waitlist DEPRECATED in v5: Remove in v6.\n    local marker = rcall(\"LINDEX\", stateKey, -1)\n    if marker and string.sub(marker, 1, 2) == \"0:\" then\n      local count = rcall(\"LLEN\", stateKey)\n      if count > 1 then\n        rcall(\"RPOP\", stateKey)\n        results[#results+1] = count-1\n      else\n        results[#results+1] = 0\n      end\n    else\n      results[#results+1] = rcall(\"LLEN\", stateKey)\n    end\n  elseif ARGV[i] == \"active\" then\n    results[#results+1] = rcall(\"LLEN\", stateKey)\n  else\n    results[#results+1] = rcall(\"ZCARD\", stateKey)\n  end\nend\nreturn results\n" "1" "bull:NotifsManager:" "active" "completed" "delayed" "failed" "paused" "prioritized" "wait" "waiting-children"
1719114360.951730 [0 lua] "LLEN" "bull:NotifsManager:active"
1719114360.951735 [0 lua] "ZCARD" "bull:NotifsManager:completed"
1719114360.951737 [0 lua] "ZCARD" "bull:NotifsManager:delayed"
1719114360.951739 [0 lua] "ZCARD" "bull:NotifsManager:failed"
1719114360.951741 [0 lua] "LINDEX" "bull:NotifsManager:paused" "-1"
1719114360.951743 [0 lua] "LLEN" "bull:NotifsManager:paused"
1719114360.951744 [0 lua] "ZCARD" "bull:NotifsManager:prioritized"
1719114360.951745 [0 lua] "LINDEX" "bull:NotifsManager:wait" "-1"
1719114360.951746 [0 lua] "LLEN" "bull:NotifsManager:wait"
1719114360.951747 [0 lua] "ZCARD" "bull:NotifsManager:waiting-children"
1719114360.952642 [0 172.20.0.1:50028] "hexists" "bull:NotifsManager:meta" "paused"
1719114362.268880 [0 172.20.0.1:49996] "bzpopmin" "bull:NotifsManager:marker" "10"
1719114362.871967 [0 172.20.0.1:50220] "bzpopmin" "bull:NotifsManager:marker" "10"
1719114363.073448 [0 172.20.0.1:60906] "bzpopmin" "bull:NotifsManager:marker" "10"
1719114363.173831 [0 172.20.0.1:32874] "bzpopmin" "bull:NotifsManager:marker" "10"
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by roggervalf** [comment]
hope this is helpful https://www.dragonflydb.io/error-solutions/redis-command-timeout-exception dragonfly team wrote about this error

**Comment by vedharish** [comment]
@roggervalf Can we make the `1000 secs` buffer configurable from options [here](https://github.com/taskforcesh/bullmq/blob/490d902c1baf28d8785989ec78f263783ca9cf81/src/classes/worker.ts#L697-L699)?

Its not always redis being slow, for us redis is hosted externally and has some RTT time impact as well

```bash
➜  redis-cli -h 10.64.136.22 --latency                                                              
min: 219, max: 813, avg: 247.87 (503 samples)^C
```

If I run bzpopmin in a loop with 5 as timeout value, once every 5-6 mins, the blocking call takes more than 6 mins

```bash
➜  while true; do time redis-cli -h 10.64.136.22 bzpopmin bull:test_test:marker 5; done
(nil)
redis-cli -h 10.64.136.22 bzpopmin bull:test_test:marker 5  0.00s user 0.00s system 0% cpu 5.526 total
(nil)
redis-cli -h 10.64.136.22 bzpopmin bull:test_test:marker 5  0.01s user 0.01s system 0% cpu 5.511 total
(nil)
redis-cli -h 10.64.136.22 bzpopmin bull:test_test:marker 5  0.01s user 0.01s system 0% cpu 5.717 total
(nil)
redis-cli -h 10.64.136.22 bzpopmin bull:test_test:marker 5  0.01s user 0.00s system 0% cpu 6.208 total
(nil)
redis-cli -h 10.64.136.22 bzpopmin bull:test_test:marker 5  0.01s user 0.01s system 0% cpu 5.567 total
(nil)
redis-cli -h 10.64.136.22 bzpopmin bull:test_test:marker 5  0.00s user 0.00s system 0% cpu 5.633 total
(nil)
redis-cli -h 10.64.136.22 bzpopmin bull:test_test:marker 5  0.01s user 0.00s system 0% cpu 5.510 total
(nil)
redis-cli -h 10.64.136.22 bzpopmin bull:test_test:marker 5  0.01s user 0.01s system 0% cpu 5.546 total
(nil)
redis-cli -h 10.64.136.22 bzpopmin bull:test_test:marker 5  0.00s user 0.00s system 0% cpu 5.506 total
(nil)
redis-cli -h 10.64.136.22 bzpopmin bull:test_test:marker 5  0.01s user 0.00s system 0% cpu 5.509 total
(nil)
redis-cli -h 10.64.136.22 bzpopmin bull:test_test:marker 5  0.01s user 0.01s system 0% cpu 5.576 total
(nil)
redis-cli -h 10.64.136.22 bzpopmin bull:test_test:marker 5  0.01s user 0.00s system 0% cpu 5.527 total
(nil)
redis-cli -h 10.64.136.22 bzpopmin bull:test_test:marker 5  0.01s user 0.00s system 0% cpu 5.501 total
(nil)
redis-cli -h 10.64.136.22 bzpopmin bull:test_test:marker 5  0.01s user 0.01s system 0% cpu 5.512 total
(nil)
redis-cli -h 10.64.136.22 bzpopmin bull:test_test:marker 5  0.01s user 0.01s system 0% cpu 5.752 total
(nil)
redis-cli -h 10.64.136.22 bzpopmin bull:test_test:marker 5  0.01s user 0.01s system 0% cpu 5.660 total
(nil)
redis-cli -h 10.64.136.22 bzpopmin bull:test_test:marker 5  0.01s user 0.01s system 0% cpu 5.514 total
(nil)
redis-cli -h 10.64.136.22 bzpopmin bull:test_test:marker 5  0.01s user 0.01s system 0% cpu 5.494 total
(nil)
redis-cli -h 10.64.136.22 bzpopmin bull:test_test:marker 5  0.01s user 0.01s system 0% cpu 5.580 total
(nil)
redis-cli -h 10.64.136.22 bzpopmin bull:test_test:marker 5  0.01s user 0.01s system 0% cpu 5.520 total
(nil)
redis-cli -h 10.64.136.22 bzpopmin bull:test_test:marker 5  0.01s user 0.01s system 0% cpu 5.515 total
(nil)
redis-cli -h 10.64.136.22 bzpopmin bull:test_test:marker 5  0.01s user 0.01s system 0% cpu 5.516 total
(nil)
redis-cli -h 10.64.136.22 bzpopmin bull:test_test:marker 5  0.01s user 0.00s system 0% cpu 5.565 total
```

**Comment by manast** [comment]
> If I run bzpopmin in a loop with 5 as timeout value, once in a while, the blocking call takes more than 6 mins

Do you have a theory on why this would happen? According to redis documentation the blocking command will expire after the block timeout value, otherwise it would be a bug in Redis as far as I can tell.

**Comment by manast** [comment]
@vedharish which version of Redis are you using?

**Comment by vedharish** [comment]
```
redis_version:5.0.9
```

My redis server is hosted in a different region from the application server where bullmq worker is running.
A simple TCP packet RTT is high (you can see from the --latency command)
redis might be responding just after 5 secs on `bzpopmin bull:test_test:marker 5` but due to high RTT, client is sometimes getting this after 6 secs

**Comment by manast** [comment]
aha, ok, you said 6 mins, so thats why I was surprised by it. Yes, then it is normal. But this timeout is only relevant when your queue is empty, i.e. there are no jobs to process. In fact normally it could be increased a lot without affecting performance. The other case when this timeout is used is when you have delayed jobs, unfortunately if the network is slow it is not really possible to do anything about it, it works in a best-effort basis.

**Comment by vedharish** [comment]
My bad - i meant 6 secs

Can we make the 1 sec buffer time between `bzpopmin` and client side `setTimeout` to force disconnect to be configurable via options? I can make a PR

**Comment by manast** [comment]
> My bad - i meant 6 secs
> 
> Can we make the 1 sec buffer time between `bzpopmin` and client side `setTimeout` to force disconnect to be configurable via options? I can make a PR

Can you explain a bit more what you mean and how would it improve the situation?

**Comment by Marsup** [comment]
Hi, I'm trying to debug the same error but for a different reason, and while I don't have a reproduction to provide, it appears to be easily reproduced when under a bit of load, by not giving enough room for the event loop.

I traced one such execution by adding 2 logs: one in the timeout and one right after the await bzpopmin. I got a few failures, here's a sample:

```
Timeout triggered for run 120: 131535.641512
Timeout triggered for run 121: 131535.757855
BZPOPMIN resolved for run 120: 131537.464672
BZPOPMIN resolved for run 121: 131537.591939
```
I added a counter to identify each run, the timers are done with performance.now().

So as you can see, bzpopmin is resolved right after the timeout, but it's quite close. I have no proof, but it feels like both codes are waiting to be executed, but the setTimeout goes first, which goes against what I believed about micro-task queue vs timers, so I'm very surprised by this result. Could it be that ioredis is using timers internally so its timer is really setup after the setTimeout, making it go first? I'm not sure.

I tried playing with the `+1000` as mentioned above, it makes no difference, unless you go above the duration for which the event loop is locked, what matters is the execution order when the event loop wakes up, so I don't think providing access to that is desirable nor effective in this scenario.

I've tried creating the bzpopmin before the setTimeout and only awaiting after, it made no difference. Unless you have a better solution, I'd suggest only causing a disconnect if once entered the setTimeout, the value is still not resolved after another setTimeout(0). What do you think?

**Comment by Marsup** [comment]
For the record, I dogfooded my own solution, which looks like this:
```ts
                    let result; 
                    // We cannot trust that the blocking connection stays blocking forever 
                    // due to issues in Redis and IORedis, so we will reconnect if we 
                    // don't get a response in the expected time. 
                    timeout = setTimeout(async () => { 
                        timeout = setTimeout(() => { 
                            if (!result) { 
                                bclient.disconnect(!this.closing); 
                            } 
                        }, 0);  
                    }, blockTimeout * 1000 + 1000); 
                    this.updateDelays(); // reset delays to avoid reusing same values in next iteration 
                    // Markers should only be used for un-blocking, so we will handle them in this 
                    // function only. 
                    result = await bclient.bzpopmin(this.keys.marker, blockTimeout);
```
It never ever entered the 2nd timeout, it was getting cancelled before it was even executed, so I think we can even skip the test on `result`

**Comment by manast** [comment]
@Marsup regarding these logs:
```
Timeout triggered for run 120: 131535.641512
Timeout triggered for run 121: 131535.757855
BZPOPMIN resolved for run 120: 131537.464672
BZPOPMIN resolved for run 121: 131537.591939
```

In principle the workers are designed to call BZPOPMIN only once, and never call it again until the previous call has completed or timed-out... maybe thats the issue, that this is not holding true in all cases?

**Comment by manast** [comment]
> So as you can see, bzpopmin is resolved right after the timeout, but it's quite close. I have no proof, but it feels like both codes are waiting to be executed, but the setTimeout goes first, which goes against what I believed about micro-task queue vs timers, so I'm very surprised by this result. Could it be that ioredis is using timers internally so its timer is really setup after the setTimeout, making it go first? I'm not sure.

But this is correct right? when the timeout calls bclient.disconnect it is expected that the call to bzpopmin completes, otherwise it will hang there forever, thats the point of the timeout. If you refer to a possible edge case where both the timeout and the bzpopmin completes almost simultaneously, I do not see how that would be a problem either.

**Comment by Marsup** [comment]
My bad about the logs, I should probably have explained that there are multiple workers, and the runs are probably from different sources. I've seen more simultaneous logs with the same pattern in other attempts, but I thought providing only a couple would be enough.

From my understanding, the setTimeout is here to prevent a stalled connection where bzpopmin wouldn't either answer or timeout itself in a timely fashion. But since holding the event loop long enough roughly around the time where bzpopmin is supposed to answer apparently causes the setTimeout to go first, it's not like redis failed to answer properly, but rather that nodejs failed to process them in the right order. I'm not even talking about completing almost simultaneously here, as without nodejs load, redis answers almost to the millisecond to that bzpopmin, but with a busy event loop, the order is wrong. Otherwise, I don't think my setTimeout(0) fix would have consistently worked (which it has).

**Comment by manast** [comment]
The thing is that it does not matter that much if the "order is wrong", as the timeout time has passed anyways. This time is used for timing, so basically everything should just be working normally.

**Comment by Marsup** [comment]
So your recommendation would be to ignore disconnections in terms of errors?

**Comment by manast** [comment]
> So your recommendation would be to ignore disconnections in terms of errors?

What are disconnections in this context? if you mean that you get a lot of disconnections from Redis then that is obviously not good and should be analysed, but that is out of the scope of BullMQ and more a question for devops.

**Comment by Marsup** [comment]
Disconnections are those triggered by that setTimeout in BullMQ, the redis server is not actively disconnecting clients.

**Comment by manast** [comment]
The timeout is there precisely to workaround the fact that sometimes IORedis does not complete blocking commands such as BZPOPMIN after the specified timeout, which in my tests was related to a quick disconnection and reconnection to a Redis server.
