### ISSUE TITLE
ERR user_script:36: bad argument #1 to 'unpack' (string expected, got nil) with empty Redis cache

### ISSUE THREAD

**Issue by gaurangparmar89** [taskforcesh/bullmq#2638]
I'm encountering an error when trying to initialize a BullMQ worker with an empty Redis cache. The error occurs even when there's no data in Redis, which seems unexpected.

Error message:
ReplyError: ERR user_script:36: bad argument #1 to 'unpack' (string expected, got nil) script: 762279fdd5e160218e47de08664b7b833401cc03, on @user_script:36.

Environment:
- BullMQ version: 4.13.0
- Redis version: 4.1.0

I was trying to implement rate limiting earlier and might have had a few stalled jobs due to the same but have cleared all redis data post that.

**Comment by manast** [comment]
If you provide a small test case that reproduces the issue we can easily tell you what is wrong with it, seems like you are passing an invalid argument somewhere.

**Comment by maxdeichmann** [comment]
@manast i had the same issue when having two different bullmq versions installed in the same project. Maybe this helps you.

**Comment by manast** [comment]
@maxdeichmann unfortunately not. Code that reproduces the issue is what we would need in order to investigate the issue.

**Comment by roggervalf** [comment]
@maxdeichmann but why you are using different versions. It should be better to use the same

**Comment by maxdeichmann** [comment]
I did not do that on purpose. I am using a monorepo where one package in the repo had another bull version as another one. As soon as both had the same version, everything was fine.

**Comment by manast** [comment]
> I did not do that on purpose. I am using a monorepo where one package in the repo had another bull version as another one. As soon as both had the same version, everything was fine.

What it seems to be the culprit for your particular case is that one version of BullMQ is using the Lua script of a different version of BullMQ. AFAIK this should be impossible to happen, as the Lua scripts are mapped by a sha256 key of its contents, so it should not be possible, but clearly somehow it can happen. This is worthy to investigate, as it is reasonable to use different versions of BullMQ against the same Redis instance.

**Comment by ert78gb** [comment]
I got similar error

``` log
ReplyError: ERR user_script:122: bad argument #1 to 'abs' (number expected, got nil) script: ef9feb35a83fa9a8c571510f20e2d57c75f68fd3, on @user_script:122.
at parseError (/opt/app/node_modules/redis-parser/lib/parser.js:179:12)
at parseType (/opt/app/node_modules/redis-parser/lib/parser.js:302:14) {
command: {
  name: 'evalsha',
  args: [
    ...
  ]
}
```

Our use case is same. We use 1 redis instance with different version of BullMQ because we have many different jobs and they are grouped by business domain. I think does not matter someone use poly or mono repo for development. We always have version conflict because we try to rolling update only 1 service/job at time. 

Not user friendly to get the error message every time when a new queue is creating.

We use bullmq 5.44.x versions

Thanks for the lib

**Comment by manast** [comment]
In principle after v5.20.0 it should not be a problem to mix different versions of BullMQ as the lua scripts are prefixed the the given version. https://github.com/taskforcesh/bullmq/compare/v5.20.0...v5.20.1

**Comment by ert78gb** [comment]
thx for the quick response.

I double checked every job and our oldest bullmq version is `5.41.7` and the newest is `5.44.4`. The `5.44.4` went live few hours ago and dropped the above errors when created new queues. De use docker image as a deployment unit. This docker image contains 1 web server and 2 worker with 2 queue. Job retry is 5

When we install a brand new job we send test messages only one at a time to test all setup are correct. It happened today too. 
- docker instance 1 starts
   - init worker 1 that processes jobs from queue 1
   - init worker 2 that processes jobs from queue 2
- docker instance 2 starts
   - init worker 1 that processes jobs from queue 1
   - init worker 2 that processes jobs from queue 2
- docker instance 1 got an http request,
  -  it created or tried to create the queue 1 but failed with the above error. I did not check the queue created or not. I just saw it in the logs.
  -  re-sent the http request. The same instance processed it successfully. Job 1 in the queue 1
- docker instance 2 (Instance 2 selected by bullmq)
   - read the a job 1 from queue 1.
   - transform it and try to put in queue 2. It failed with the same error.
   - 2nd attempt success

We use a singleton redis instance to prevent multiple connections and this way we could correctly close the connections when stop or redeploy a service. The default implementation did not handled properly the graceful shutdown. 
The redis config is very simple
```
{
	db: Number(process.env.REDIS_DB) || 0,
	host: process.env.REDIS_HOST,
	password: process.env.REDIS_PASSWORD,
	port: Number(process.env.REDIS_PORT) || 6379,
	username: process.env.REDIS_USER,
	// eslint-disable-next-line unicorn/no-null
	maxRetriesPerRequest: null, // BullMQ: Your redis options maxRetriesPerRequest must be null.
}
```
We use `ioredis@5.6.0`

We have 1 redis instance in production. We use the `redis:7.4.2-alpine3.21` docker image. 
We use 2 database on this instance because we have 4 legacy job that uses `bull@4.16.5`
- Database 0 for `bull@4.16.5`
- Database 1 for bullmq

My assumption is bull and bullmq should not interfere because they use 2 redis db. 

I don't know it is matter or not, but the first bullmq version that we used when created the first queue in the database 1 was `2.3.2`

I never experienced this issue when we run isolated e2e test. In these tests only one bullmq version connects to a dedicated redis instance

Sorry for the long message but maybe it could highlight something. Maybe we misuse something.

**Comment by manast** [comment]
Maybe it is something else. Are you using typescript? a common issue is when using plain javascript you can send invalid arguments or options that can lead to errors in the lua scripts. We would need some code to reproduce the issue in order to be able to dig deeper into it.

**Comment by ert78gb** [comment]
I don't use typescript. I more trust in proper test. I don't think it is a "typo" issue because for the 2nd try everything works and it occurs when first time creating the queue. 

I will try to create a reproduction repo at the end of this week or on the next week.

**Comment by manast** [comment]
If it happens always the first try then it should be possible to reproduce it.

**Comment by manast** [comment]
Btw, please open a new issue as the error in this issue is unrelated to the one you got.

**Comment by manast** [comment]
Anyway, I think I know why this is happening to you, you are using the limiter option but not passing the duration, so this fails:
https://github.com/taskforcesh/bullmq/blob/master/src/commands/includes/prepareJobForProcessing.lua#L22
Since you are using plain javascript, you are not getting a compiling error when this option is missing.

**Comment by ert78gb** [comment]
You are right I used `limiter.max` instead of `concurrency`.

[OFF] My opinion is not enough to use typescript to build proper validation. The `limiter: {max: 1, duration: 0}` satisfy typescript and the lua script  also will not complain, but I don't know what is the expected behaviour when the `duration` is 0.

My last question is if I deploy a new version with the proper `concurrency` option then will it update the queue or recommended drop and recreate the queue? 

Sorry for I polluted this issue.

Thx for the help and for the lib.

**Comment by manast** [comment]
You do not need to recreate the queue as this setting is just alive while the worker instance is alive.
We put in place some safeguards against invalid values, and for a duration of 0 indeed it should be protected. But in general you will avoid many dumb mistakes like this one if your type system captures them early. In general we will not pursue defensive programming as this is easy to overlook by human developers, and instead leave this work to the compiler as much as we can.

**Comment by manast** [comment]
I am closing this issue now as there is no code to reproduce it and it does not seem like something that is happening to other users.
