### ISSUE TITLE
[Bug]: Upgrate from nodejs 21 to nodejs 22 throws RangeError

### ISSUE THREAD

**Issue by dimonnwc3** [taskforcesh/bullmq#2747]
### Version

5.12.12

### Platform

NodeJS

### What happened?

Everything worked fine using nodejs 21, but after upgrade to nodejs 22, `add` method in `flowProducer` throws an error. Likely `job.add` does the same as it's used internally according to stack trace.

### How to reproduce.

call `flowProducer.add` method

### Relevant log output

```shell
RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: "length" is outside of buffer bounds
    at proto.utf8Write (node:internal/buffer:1066:13)
    at Packr.encodeUtf8 (/app/node_modules/msgpackr/pack.js:31:18)
    at pack (/app/node_modules/msgpackr/pack.js:320:15)
    at packArray (/app/node_modules/msgpackr/pack.js:234:5)
    at pack (/app/node_modules/msgpackr/pack.js:420:7)
    at Packr.pack.encode (/app/node_modules/msgpackr/pack.js:129:6)
    at Scripts.addStandardJob (/app/node_modules/bullmq/src/classes/scripts.ts:158:15)
    at Scripts.addJob (/app/node_modules/bullmq/src/classes/scripts.ts:219:27)
    at Job.addJob (/app/node_modules/bullmq/src/classes/job.ts:1189:25)
    at FlowProducer.addNode (/app/node_modules/bullmq/src/classes/flow-producer.ts:333:11) {
  code: 'ERR_BUFFER_OUT_OF_BOUNDS'
}
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dimonnwc3** [comment]
FYI: seems issue is in nodejs itself, here is relevant issue: https://github.com/nodejs/node/issues/54518

**Comment by manast** [comment]
we only support NodeJS versions LTS, LTS-1 and LTS-2. Version 22 is thus not supported as it is not LTS.
