### ISSUE TITLE
[Bug]:  documentation for repeat-strategies refers to cron when should be pattern

### ISSUE THREAD

**Issue by gmillerd** [taskforcesh/bullmq#2814]
### Version

5.18.0

### Platform

NodeJS

### What happened?

Documentation [repeat-strategies](https://docs.bullmq.io/guide/job-schedulers/repeat-strategies) referrs to property cron, when it should be property pattern.

### How to reproduce.

n/a

### Relevant log output

```shell
TSC with cron

TS: Object literal may only specify known properties, and 'cron' does not exist in type 

runtime with cron

error: Validation error, cannot resolve alias "und"
at /home/node/node_modules/cron-parser/lib/expression.js:169:17
at _parseField (/home/node/node_modules/cron-parser/lib/expression.js:163:21)
at parse (/home/node/node_modules/cron-parser/lib/expression.js:885:36)
at getNextMillis (/home/node/node_modules/bullmq/dist/cjs/classes/job-scheduler.js:132:40)
at /home/node/node_modules/bullmq/dist/cjs/classes/job-scheduler.js:41:39
at upsertJobScheduler (/home/node/node_modules/bullmq/dist/cjs/classes/job-scheduler.js:13:30)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manast** [comment]
Thanks for reporting this issue and sorry for the overlook. It has been fixed now.
