### ISSUE TITLE
[Bug]: RangeError when adding child job

### ISSUE THREAD

**Issue by jonknyc** [taskforcesh/bullmq#2820]
### Version

^5.18.0

### Platform

NodeJS

### What happened?

When adding a child job (following the steps documented here: https://docs.bullmq.io/patterns/process-step-jobs#waiting-children), I get an error:

```
RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: "length" is outside of buffer bounds
    at proto.utf8Write (node:internal/buffer:1066:13)
    at Packr.encodeUtf8 (/Users/jonk/celebrate2/node_modules/msgpackr/pack.js:31:18)
    at pack (/Users/jonk/celebrate2/node_modules/msgpackr/pack.js:324:15)
    at packArray (/Users/jonk/celebrate2/node_modules/msgpackr/pack.js:238:5)
    at pack (/Users/jonk/celebrate2/node_modules/msgpackr/pack.js:424:7)
    at Packr.pack.encode (/Users/jonk/celebrate2/node_modules/msgpackr/pack.js:129:6)
    at Scripts.addStandardJob (/Users/jonk/celebrate2/node_modules/bullmq/src/classes/scripts.ts:158:15)
    at Scripts.addJob (/Users/jonk/celebrate2/node_modules/bullmq/src/classes/scripts.ts:219:27)
    at Job.addJob (/Users/jonk/celebrate2/node_modules/bullmq/src/classes/job.ts:1212:25)
    at Function.create (/Users/jonk/celebrate2/node_modules/bullmq/src/classes/job.ts:254:24) {
  code: 'ERR_BUFFER_OUT_OF_BOUNDS'
}
```

If I add the job without specifying the parent details, it works.  But when I specify the parent, it fails:

```
            // create child job
            await queue.add(JobType.FOO, data, {
              parent: {
                id: job.id!,
                queue: job.queueQualifiedName,
              },
            })
```

I have confirmed that the job ID exists and everything looks correct.  As I said, I am basically copying the documentation.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Botelho31** [comment]
I believe this is a [node version error](https://github.com/nodejs/node/issues/54518 ), it should only be ocurring in version 22.7, if you could upgrade it to 22.8 or downgrade to 22.5 it should be fixed.

**Comment by xtrinch** [comment]
@Botelho31 Are we sure about that? I'm getting this same error in node 20.18.0

**Comment by duckboy81** [comment]
Same with node v23.0.0

**Comment by manast** [comment]
v23 is definitely broken, dozens of tests are just failing miserably with many obscure errors.

**Comment by manast** [comment]
Fixed here: https://github.com/taskforcesh/bullmq/pull/2882

**Comment by james-william-r** [comment]
Just a heads up, similar issue: Had the same error but when using addBulk, was on Node 23.7, downgraded to 20 and it's working fine.

**Comment by manast** [comment]
We only support NodeJS LTS versions. 23 is not supposed to be used in production, nor do we run tests on it. when v24 is out we will support it.
