### ISSUE TITLE
[Bug]: ESM build contains __dirname references again

### ISSUE THREAD

**Issue by KubaJastrz** [taskforcesh/bullmq#2845]
### Version

v5.20.0

### Platform

NodeJS

### What happened?

`__dirname` was added in this PR: https://github.com/taskforcesh/bullmq/pull/2822

Related issue from the past: https://github.com/taskforcesh/bullmq/issues/2288

Downgrading to 5.19.1 works for me

### How to reproduce.

I'm using bullmq with Remix+Vite setup which enforces use of ESM in production. Let me know if you need actual reproduction or the problem description is enough.

### Relevant log output

```
ReferenceError: __dirname is not defined
    at readPackageJson (file:///<redacted>/node_modules/.pnpm/bullmq@5.21.1/node_modules/bullmq/dist/esm/utils.js:192:14)
    at RedisConnection.init (file:///<redacted>/node_modules/.pnpm/bullmq@5.21.1/node_modules/bullmq/dist/esm/classes/redis-connection.js:151:29)
    at new RedisConnection (file:///<redacted>/node_modules/.pnpm/bullmq@5.21.1/node_modules/bullmq/dist/esm/classes/redis-connection.js:59:34)
    at new QueueBase (file:///<redacted>/node_modules/.pnpm/bullmq@5.21.1/node_modules/bullmq/dist/esm/classes/queue-base.js:35:27)
    at new Queue2 (file:///<redacted>/node_modules/.pnpm/bullmq@5.21.1/node_modules/bullmq/dist/esm/classes/queue.js:17:9)
    at file:///<redacted>/packages/queue/src/<redacted>:9:37
    at ModuleJob.run (node:internal/modules/esm/module_job:262:25)
    at ModuleLoader.import (node:internal/modules/esm/loader:475:24)
    at run (/<redacted>/node_modules/.pnpm/@remix-run+serve@2.11.2_typescript@5.6.3/node_modules/@remix-run/serve/dist/cli.js:112:15)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manast** [comment]
From version [5.21.2](https://github.com/taskforcesh/bullmq/compare/v5.21.1...v5.21.2) https://github.com/taskforcesh/bullmq/blob/master/docs/gitbook/changelog.md#5212-2024-10-22
it should be resolved as we now generate the version in release time and do not need to read the package.json anymore which is actually impossible to do in NodeJS in a reliable way.

**Comment by Pyakz** [comment]
still having this issue

**Comment by manast** [comment]
@Pyakz can you please open a new issue with your particular specifics?
