### ISSUE TITLE
[Bug]: Telemetry: Error in BullMQOTelSpan.setSpanOnContext

### ISSUE THREAD

**Issue by lovre-nc** [taskforcesh/bullmq#2894]
### Version

v7.20.1

### Platform

NodeJS

### What happened?

I tried to switch our project from @appsignal/opentelemetry-instrumentation-bullmq to the bullmq-otel package. Unfortunately the processJob method in the worker seems to fail which in turn causes the job to stall. 
An error `Cannot read properties of undefined (reading 'setValue')` is logged.

A `process` trace seems to be created when the job processing starts:
![image](https://github.com/user-attachments/assets/25bcac55-8229-411a-adf1-e71f63b55a63)

I can also see some `startStalledCheckTimer` traces if I restart the worker.

It looks like the issue is that parentcontext is undefined in here: https://github.com/taskforcesh/bullmq/blob/624a08638ff43b6fae82d9cf5cf939bdbd149f69/src/utils.ts#L333

### How to reproduce.

I can't provide reproducing code right now due to time constraints.

### Relevant log output

```shell
TypeError: Cannot read properties of undefined (reading 'setValue')
  at TraceAPI.setSpan (./node_modules/.pnpm/@opentelemetry+api@1.9.0/node_modules/@opentelemetry/api/src/trace/context-utils.ts:52:18)
  at BullMQOTelSpan.setSpanOnContext (./node_modules/.pnpm/bullmq-otel@1.0.1/node_modules/bullmq-otel/src/bullMQOtel.ts:66:18)
  at trace (./node_modules/.pnpm/bullmq@5.25.4/node_modules/bullmq/src/utils.ts:333:31)
  at WorkerPro.trace (./node_modules/.pnpm/bullmq@5.25.4/node_modules/bullmq/src/classes/queue-base.ts:198:17)
  at WorkerPro.processJob (./node_modules/.pnpm/bullmq@5.25.4/node_modules/bullmq/src/classes/worker.ts:826:17)
  at <anonymous> (./node_modules/.pnpm/bullmq@5.25.4/node_modules/bullmq/src/classes/worker.ts:524:22)
  at WorkerPro.retryIfFailed (./node_modules/.pnpm/bullmq@5.25.4/node_modules/bullmq/src/classes/worker.ts:1174:22)
  at WorkerPro.run (./node_modules/.pnpm/bullmq@5.25.4/node_modules/bullmq/src/classes/worker.ts:522:18)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manast** [comment]
I cannot find anything obvious in our code so we will wait until a reproducible test case is provided.

**Comment by Meemaw** [comment]
I just tried adding the telemetry to my project as well. Hit the error on a dummy worker.

```js
import { Worker } from "bullmq";
import { BullMQOtel } from "bullmq-otel";

const worker = new Worker(
  "get-metadata",
  async () => {
    return undefined;
  },
  {
    connection: {
      host: "localhost",
      port: 6379,
    },
    telemetry: new BullMQOtel("get-metadata"),
  }
);
```

**Comment by manast** [comment]
I just run this code without issues: ts```
import { Queue, Worker } from "bullmq";
import { BullMQOtel } from "bullmq-otel";

const worker = new Worker(
  "get-metadata",
  async () => {
    console.log("processing job");
    return undefined;
  },
  {
    connection: {
      host: "localhost",
      port: 6379,
    },
    telemetry: new BullMQOtel("get-metadata"),
  }
);

const queue = new Queue("get-metadata", {
  connection: {
    host: "localhost",
    port: 6379,
  },
  telemetry: new BullMQOtel("get-metadata"),
});

queue.add("get-metadata", { key: "value" });
```
 Can you give us more context to see if we can reproduce the issue?

**Comment by manast** [comment]
ah ok, it seems like if you do not add the telemetry option to the Queue instance you get this exception. We will fix that, however, unless you add it to the Queue instance you will not get proper traces covering all the way from job production to consumption. This is all documented here: https://docs.bullmq.io/guide/telemetry/getting-started
