### ISSUE TITLE
Intermittent ‘Missing lock for job’ Errors in BullMQ After Queue History Increase

### ISSUE THREAD

**Issue by drmarshall** [taskforcesh/bullmq#2974]
### Version

v5.7.15

### Platform

NodeJS

### What happened?

I'm a fairly new bullmq user. This is less likely a bug than a misconfiguration or known bugged version? Appreciate any insights from the maintainers or community on this issue.

Across several different services/queues, we have started to see numerous: `Missing lock for job N. moveToFinished`, which then triggers a retry and leaves the job in failed state (approximately 3-5% of jobs). Previously this was a non-existent issue for us, so it's odd for it to appear across all our queues. The only recent change is that we've increased history to 100 jobs completed jobs per queue (up from ~25-50). Some job logs can be thousands of lines; job data are at most ~400 lines of pretty-printed JSON. Did I perhaps miss something in the documentation about the important of speed/load/memory requirements for the redis instance?

I have been trying to work on a reproducible example, but I have not yet been successful – I think that it might only happen under redis load? All the issues/documentation I can find seems to suggest this type of issues is from too short of a `lockDuration` during node event loop (doesn't seem to be the case here – some jobs are only 30 seconds and non-blocking of event loop) or calling moveToFinished or related methods manually (we are not).

I looked through issues/releases for a reference to a specific changes that might resolve this if it were a known issue. Please do let me know if I missed something in the history.

### How to reproduce.

```
// src/my-service/queue.ts

import { Queue } from "bullmq"

import { getQueueConnection } from "@/lib/redis"

export const QUEUE = "my-queue"

let queue: Queue

export const getQueue = (): Queue => {
  if (!queue) {
    queue = new Queue(QUEUE, {
      connection: getQueueConnection(),
      defaultJobOptions: {
        attempts: 4,
        backoff: {
          type: "exponential",
          delay: 5000,
        },
      },
    })
    queue.on("error", (job) => {
      console.error(QUEUE, "queue error", job)
    })
  }
  return queue
}

...
// src/instrumentation.ts

const { Worker } = await import("bullmq")

export const register = async () => {
...
  if (process.env.NEXT_RUNTIME === "nodejs") {
    const worker = new Worker(
      QUEUE,
      async (job: Job & { data: MyJob }) => {
        try {
          const jobData = jobSchema.parse(job.data)
          await process(jobData, true, makeJobLogger(job))
        } catch (e) {
          console.error("Error processing my job", e)
          throw e
        }
      },
      {
        connection: getWorkerConnection(),
        concurrency: 1,
        removeOnComplete: { count: 100 },
        removeOnFail: { count: 500 },
        runRetryDelay: 1000,
        settings: {
          backoffStrategy,
        },
      }
    )
    myWorker.on("error", (err) => {
      console.error(
        "myWorker Error processing my job",
        err.message,
        err.cause,
        err.stack
      )
    })
    myWorker.on("completed", (job: Job & { data: myJob }) => {
      console.log("myWorker Job completed", job.id)
    })
  }
}

...

// src/lib/redis.ts

import IORedis from "ioredis"

import { env } from "@/env.mjs"

const retryStrategy = (times: number) => {
  return Math.max(Math.min(Math.exp(times), 20000), 1000)
}

let workerConnection: IORedis
let queueConnection: IORedis

export const getWorkerConnection = () => {
  if (!env.REDIS_URL) {
    throw new Error("REDIS_URL is not set")
  }
  if (!workerConnection) {
    workerConnection = new IORedis(env.REDIS_URL, {
      offlineQueue: true,
      maxRetriesPerRequest: null,
      enableReadyCheck: false,
      retryStrategy,
    })
  }
  return workerConnection
}

export const getQueueConnection = () => {
  if (!env.REDIS_URL) {
    throw new Error("REDIS_URL is not set")
  }

  if (!queueConnection) {
    queueConnection = new IORedis(env.REDIS_URL, {
      offlineQueue: false,
      maxRetriesPerRequest: null,
      enableReadyCheck: false,
      retryStrategy,
    })
  }
  return queueConnection
}

```

### Relevant log output

```shell
Error: Missing lock for job 1234. moveToFinished
    at finishedErrors (/usr/node_modules/bullmq/dist/cjs/classes/scripts.js:308:28)
    at <anonymous> (/usr/node_modules/bullmq/dist/cjs/classes/scripts.js:290:24)
    at processTicksAndRejections (native:7:39)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manast** [comment]
I think it would be useful if you upgrade to the latest version and we can see if you still experiment this issue before we dig deeper into it.

**Comment by manast** [comment]
It is not normal that you get this error so often, the question is what is your process function doing, is it doing a very CPU intensive operation that does not let the worker time left to update the locks and are therefore lost before the job manages to complete it?

**Comment by manast** [comment]
I don't think tweaking stalledIntervall or lockDuration is the best solution here. If the call to ffmpeg is indeed creating a new process, then the main node event loop should be able to renew the lock, so I wonder if it really is the case that it is running in a separate process?

**Comment by manast** [comment]
Btw, If you could isolate the issue in a simple to run test I can definitely look deeper into it to see what is going on.
