### ISSUE TITLE
 client.moveToActive is not a function 

### ISSUE THREAD

**Issue by lukepolo** [taskforcesh/bullmq#429]
Using the base example of 

```
import { Queue, Worker } from 'bullmq'

const connection = new IORedis({
      host: "my.host",
    });
new Queue('myqueue', { connection });

const myWorker = new Worker('myworker', async (job)=>{}, { connection });

```

TypeError: client.moveToActive is not a function
    at Function.moveToActive (webpack-internal:///./node_modules/bullmq/dist/classes/scripts.js:248:37)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Worker.moveToActive (webpack-internal:///./node_modules/bullmq/dist/classes/worker.js:145:31)

```
TypeError: client.moveToActive is not a function
    at Function.moveToActive (webpack-internal:///./node_modules/bullmq/dist/classes/scripts.js:248:37)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Worker.moveToActive (webpack-internal:///./node_modules/bullmq/dist/classes/worker.js:145:31)


```

I must be doing something wrong

**Comment by lukepolo** [comment]
webpack issue, 

`     .set("__dirname", true)`

**Comment by andrisi** [comment]
for me it happens on nodejs

**Comment by JonasHiltl** [comment]
I also started encountering this error since yesterday. Recent updates must be causing this because the setup I'm using worked until yesterday.
```
TypeError: client.moveToActive is not a function
   at Function.moveToActive (/home/.../node_modules/bullmq/dist/classes/scripts.js:417:37)
   at processTicksAndRejections (node:internal/process/task_queues:96:5)
   at async Worker.moveToActive (/home/.../node_modules/bullmq/dist/classes/worker.js:206:35)
```
I'm using BullMQ with Fastify and the function below is a plugin I have created that allows me to create Queues and Workers based on folder structure. 
```typescript
/**
 * Load every worker function inside a specified directory
 * @param {Object} fastify - Fastify instance
 * @param {Object} opts - Plugin's options
 */
const fastifyBullMQ = async (
  fastify: FastifyInstance,
  opts: FastifyQueueOptions
) => {
  const queues = {};
  const workers = {};

  const files = fg.sync(opts.bullPath);

  files.forEach(async (filePath) => {
    try {
      const parts = filePath.split('/');
      const queueName = parts[parts.length - 2];

      const {
        default: worker,
        queueConfig,
        workerConfig,
      } = await import(path.resolve(filePath));

      (queues as any)[queueName] = new Queue(queueName, {
        connection: opts.connection,
        ...(queueConfig && queueConfig),
      });

      if (!worker) {
        fastify.log.warn(
          `The queue ${queueName} does not have a worker function`
        );
      } else {
        (workers as any)[queueName] = new Worker(
          queueName,
          (job) => worker(fastify, job),
          {
            connection: opts.connection,
            ...(workerConfig && workerConfig),
          }
        );
      }
    } catch (error) {
      console.log('Catched error', error);
    }
  });

  fastify.decorate('queues', queues);
  fastify.decorate('workers', workers);
};
```

**Comment by manast** [comment]
@JonasHiltl https://github.com/taskforcesh/bullmq/issues/946#issuecomment-996360213
