### ISSUE TITLE
Wrong redis version recognition when using AWS ElastiCache

### ISSUE THREAD

**Issue by ScripterSugar** [taskforcesh/bullmq#437]
I keep getting this error when I try to use bullmq with my ElastiCache redis instance.

```
Error: Redis version needs to be greater than 5.0.0 Current: 4.0.9
    at RedisConnection.init (/home/ubuntu/vendit/vendit-reservation-service/node_modules/bullmq/src/classes/redis-connection.ts:80:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

But my instance uses redis 6.0.5

Here's my instance information from AWS.

![image](https://user-images.githubusercontent.com/19164553/112069094-8a8d0480-8bae-11eb-9476-8e84ca57d21b.png)

I can confirm this, because I just created the instance from AWS console, with most recent settings.

I need to use BullMQ because a lot of codes I wrote are depending to this library..

I also tried to create 5.x version instance in ElastiCache, but it didn't work, too.

Any solution for this?

**Comment by ScripterSugar** [comment]
Here's the redis_version from info query to my redis server using redis-cli.

![image](https://user-images.githubusercontent.com/19164553/112070777-bfe72180-8bb1-11eb-8353-45c9475202c3.png)

The server response have no problem... I wonder why bullMQ recognizes my server as 4.0.9

**Comment by ScripterSugar** [comment]
Oops, I found that my bullMQ wasn't connecting to ElastiCache but my local instance. Sorry for the disturbance.
