### ISSUE TITLE
TypeError: Do not know how to serialize a BigInt

### ISSUE THREAD

**Issue by nshusr** [taskforcesh/bullmq#447]
use graphql bigint

Maybe this can solve this problem https://github.com/GoogleChromeLabs/jsbi/issues/30#issuecomment-521460510

``` bash
(node:48282) UnhandledPromiseRejectionWarning: TypeError: Do not know how to serialize a BigInt
    at JSON.stringify (<anonymous>)
    at Job.asJSON (/Users/mac/code/oe-tr-be-prisma/node_modules/.pnpm/bullmq@1.15.1/node_modules/bullmq/src/classes/job.ts:159:18)
    at Job.addJob (/Users/mac/code/oe-tr-be-prisma/node_modules/.pnpm/bullmq@1.15.1/node_modules/bullmq/src/classes/job.ts:484:26)
    at Function.create (/Users/mac/code/oe-tr-be-prisma/node_modules/.pnpm/bullmq@1.15.1/node_modules/bullmq/src/classes/job.ts:73:24)
```

**Comment by nshusr** [comment]
that is BigInt toString not support , use that fix https://github.com/sqlpad/sqlpad/pull/522/files#diff-0aa0012567e019496f013711295caf673494e57804401f2de215549959f7f848R93

**Comment by pedropmedina** [comment]
I'm having the same issue when dealing with bigint and yes we can handle it locally with the example provided on [mdn](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt#use_within_json), but shouldn't this be taken care of by bullmq instead wherever they make use of JSON.stringify?
