### ISSUE TITLE
Connection is closed

### ISSUE THREAD

**Issue by zwjohn** [taskforcesh/bullmq#670]
I am getting the following error after upgrading to 1.40.1

| Error: Connection is closed.
        |     at Redis.endHandler (/var/www/api/rest-server/node_modules/bullmq/dist/classes/redis-connection.js:53:24)
        |     at Object.onceWrapper (events.js:422:26)
        |     at Redis.emit (events.js:315:20)
        |     at processTicksAndRejections (internal/process/task_queues.js:75:11)

this happens when shutting down the server where my code was trying to close bullmq connections with code below
    
queueScheduler && await queueScheduler.close();
    queue.getTaskQueue() && await queue.getTaskQueue().close();
    worker && await worker.close();

**Comment by manast** [comment]
@zwjohn can you isolate the issue in some reproducible test case please?

**Comment by tayclark** [comment]
I'm running into a similar issue. @zwjohn ooc are you on an M1 mac?

**Comment by zwjohn** [comment]
nope, this was on the node server on ubuntu, I had to remove the queueScheduler.close() and queue.close(), and only keep the woker.close() and the error is no more. It seems one of the close() functions also closed the connection of the worker.

**Comment by roggervalf** [comment]
@zwjohn could you please try last version to see if you are still having this issue?

**Comment by roggervalf** [comment]
@mannharleen could you please elaborate your issue in a piece of code, a reproducible test case would be great to take a look on it.

**Comment by mannharleen** [comment]
@Trystan-C @roggervalf 
(I think) I've been able to pin point something here - 
The issue seems to be with creating a new Worker after a prev worker has been closed (assuming both use the same underlying ioredis connection). ie. 
```
let worker1 = new Worker('_Sync_Execution_History', null, workerConstructorOptions)
await worker1.close()
let worker2 = new Worker('_Sync_Execution_History', null, workerConstructorOptions)
```
- if i comment either of lines 2 or 3 above, no error is thrown

**Comment by mannharleen** [comment]
> @mannharleen that seems to indicate that the shared connection has been closed after closing the first worker. Any chance to refine the above code into a snippet I can run and test myself?

Surprisingly the underlying redis connect status = ready. It doesnt seem to get closed
Here is a very close resemblance to my actual code- 
```js
const { Queue, Worker, QueueScheduler } = require('bullmq');
const IORedis = require('ioredis');


(async () => {
node= {}
node.conSettings = {
    host: host, // you ll have to declare these of course
    port: port,
    password: token,
    tls: { servername: host }
}
node.ioredisConnection = new IORedis(node.conSettings);
await new Promise(r => setTimeout(r, 1000)) // some timeout to make sure conn is ready state

console.log('!!!w1', node.ioredisConnection.status);
let workerConstructorOptions = {
    ...{
        connection: node.ioredisConnection,
        maxStalledCount: 2,
        stalledInterval: 30000
    }, 
  "lockDuration": 5 * 60 * 1000
  }
let worker1 = new Worker('_Sync_Execution_History', null, workerConstructorOptions)
console.log('!!!w2', node.ioredisConnection.status);
await worker1.close()
console.log('!!!w3', node.ioredisConnection.status);
let worker2 = new Worker('_Sync_Execution_History', null, workerConstructorOptions)
console.log('!!!w4', node.ioredisConnection.status);    
})();
```

**Comment by mannharleen** [comment]
@manast I've been able to fix this issue. 

The issue popped up since `v1.44.3`, I tested the versions to arrive at this conclusion - 
```
v1.14.4 is good
v1.40.1 is good
v1.41.0 is good
v1.43.0 is good
v1.44.0 is good
v1.44.2 is good
v1.44.3 is bad = throws `Error: Connection is closed.`
v1.45.0 is bad = throws `Error: Connection is closed.`
v1.49.0 is bad = throws `Error: Connection is closed.`
```

Looking at release `v1.44.3`, I see a reference to a new option called `sharedConnection`. [here](https://github.com/taskforcesh/bullmq/compare/v1.44.2...v1.44.3)

In my testing code snippet above, when I include `sharedConnection: true` in `workerConstructorOptions` , I dont see the connection is closed error anymore. I believe the default value for sharedConnection = false

Q. I am not across the code base fully so cant be sure of my finding, but does this make sense @manast ?

**Comment by manast** [comment]
If you check in redis-connection.ts, it will only close the redis connection with quit if the connection is not shared. In this case since it should be shared it should not disconnect. I am checking this now anyway, will have a fix soon hopefully.

**Comment by Trystan-C** [comment]
@manast The issue appears to be fixed for me! Thanks @mannharleen, @roggervalf, and @manast for the quick turn around on this!

**Comment by mannharleen** [comment]
@manast Thanks for the quick fix. Do you mind adding a test case so this is caught if it happens again?
Or would you like me to add one in there https://github.com/taskforcesh/bullmq/blob/2c7ab4472144e9184d8dad9a8a113e9bfef7283a/src/test/test_worker.ts

**Comment by roggervalf** [comment]
@mannharleen if you could add one, it would be very nice

**Comment by roggervalf** [comment]
> @roggervalf I am on my way to adding one joy

lol xd

**Comment by manast** [comment]
https://github.com/taskforcesh/bullmq/pull/824

**Comment by mannharleen** [comment]
> @roggervalf I am on my way to adding one 😂

Awesome 🥇
