### ISSUE TITLE
QueueScheduler & QueueEvents make the test suite suspend

### ISSUE THREAD

**Issue by shahinghasemi** [taskforcesh/bullmq#721]
This is the simplified version of our code base to reproduce the bug.
```
const Redis = require('ioredis')
const {QueueScheduler} = require('bullmq')

const connection1 = new Redis(6379, 'localhost')

let queueScheduler;
describe('test', ()=>{
    beforeAll(()=>{
        queueScheduler = new QueueScheduler('q1', {connection: connection1})
    })

    afterAll(async()=>{
        await queueScheduler.close()
        // await connection1.quit()
    }, 10000)
    
    it('nothin', ()=>{
        expect(true).toBe(true)
    })
})
```
The expected behavior is that teardown phase should successfully close the connection and test should end smoothly, but when running the test, it's suspended and throws this warnings: 
```
Jest did not exit one second after the test run has completed.
This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
```
When run the test with `--detectOpenHandles` option it complains about the Redis connection and Queuescheduler.

This condition makes our CI pipeline fail randomly because of timeout limit and I'm looking for a way to close the connections smoothly.

Environment:
`bullmq`: 1.44.2
`ioredis`: 4.27.8
`redis`: 6.0.9

**Comment by shahinghasemi** [comment]
Hi again, I upgraded the package to the latest(`1.46.0`), but it seems the problem exists though. I just run the test above and **test is getting suspended**  again, with error below: 

```
console.error
    Error [ERR_UNHANDLED_ERROR]: Unhandled error. (Error: Connection is closed.
        at Redis.endHandler (/home/shahin/codes/jest/node_modules/bullmq/src/classes/redis-connection.ts:78:16)
        at Object.onceWrapper (events.js:422:26)
        at Redis.emit (events.js:315:20)
        at processTicksAndRejections (internal/process/task_queues.js:75:11))
        at QueueScheduler.emit (events.js:304:17)
        at QueueScheduler.emit (/home/shahin/codes/jest/node_modules/bullmq/src/classes/queue-base.ts:45:20)
        at RedisConnection.emit (events.js:315:20)
        at /home/shahin/codes/jest/node_modules/bullmq/src/classes/redis-connection.ts:48:26
        at processTicksAndRejections (internal/process/task_queues.js:93:5) {
      code: 'ERR_UNHANDLED_ERROR',
      context: Error: Connection is closed.
          at Redis.endHandler (/home/shahin/codes/jest/node_modules/bullmq/src/classes/redis-connection.ts:78:16)
          at Object.onceWrapper (events.js:422:26)
          at Redis.emit (events.js:315:20)
          at processTicksAndRejections (internal/process/task_queues.js:75:11)
    }

      at QueueScheduler.emit (node_modules/bullmq/src/classes/queue-base.ts:51:17)

  console.error
    Error: Connection is closed.
        at Redis.endHandler (/home/shahin/codes/jest/node_modules/bullmq/src/classes/redis-connection.ts:78:16)
        at Object.onceWrapper (events.js:422:26)
        at Redis.emit (events.js:315:20)
        at processTicksAndRejections (internal/process/task_queues.js:75:11)
```
And jest is complaining about the suspension: 
```
Jest did not exit one second after the test run has completed.
This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
```

**Comment by manast** [comment]
Thats a legit error, since you are closing while the queue is initializing, you need to listen for errors to avoid it.

**Comment by shahinghasemi** [comment]
How about suspension? How the teardown phase should close the connections for both `bullmq` and `redis`? I used `waitUntilReady` but the redis error still exists!

**Comment by shahinghasemi** [comment]
The Issue still exists buddy! I tested it with `Queue`, `QueueEvents` and it seems the connection is properly closed, however for `QueueScheduler` it throws the same error: 
```
Error: Connection is closed.
        at close (/home/shahin/codes/proj/node_modules/ioredis/built/redis/event_handler.js:183:25)
        at Socket.<anonymous> (/home/shahin/codes/proj/node_modules/ioredis/built/redis/event_handler.js:150:20)
        at Object.onceWrapper (events.js:422:26)
        at Socket.emit (events.js:315:20)
        at TCP.<anonymous> (net.js:673:12)

**Comment by manast** [comment]
Weird, my test code works perfectly:
```ts
const Redis = require("ioredis");
const { QueueScheduler } = require("bullmq");

const connection1 = new Redis(6379, "localhost");

const start = async () => {
  const queueScheduler = new QueueScheduler("q1", { connection: connection1 });
  await queueScheduler.waitUntilReady();
  await queueScheduler.close();
  await connection1.quit();
};

start();
```

**Comment by shahinghasemi** [comment]
I just copied your snippet and run it, but the error still exists. this is my environment:
`node`:  14.15.5
`bullMQ`:  1.46.1
`ioredis`: 4.27.8
`redis`: tried with `6.0.9-alpine` and `latest` images(I run the Redis through container).

Would you tell about your environment? Is there any difference between yours and mine?

**Comment by shahinghasemi** [comment]
Hello dear @manast I guess the error still exists. any workaround?

**Comment by roggervalf** [comment]
@shahinghasemi I tried your piece of code, and you need to close connection1 too:
```js
const Redis = require('ioredis')
const {QueueScheduler} = require('bullmq')

const connection1 = new Redis(6379, 'localhost')

let queueScheduler;
describe('test', ()=>{
    beforeAll(()=>{
        queueScheduler = new QueueScheduler('q1', {connection: connection1});
    })

    afterAll(async()=>{
        await queueScheduler.close()
        await connection1.quit()
    }, 10000)
    
    it('nothing', ()=>{
        expect(true).toBe(true)
    })
})
```
