### ISSUE TITLE
Intermittent Connection is closed error

### ISSUE THREAD

**Issue by shahinghasemi** [taskforcesh/bullmq#878]
Hello, we're encountering random `connection is closed` error in our integration tests. I'm not sure what exactly is the problem however I have a code snippet that can produce the same error with high frequency(not 100% of the times).
```
const start = async () => {
    const connection1 = new Redis({
        enableReadyCheck: false,
        maxRetriesPerRequest: null,
        enableOfflineQueue: false,
        showFriendlyErrorStack: true,
    })
    const queueScheduler = new QueueScheduler("q1", { connection: connection1 });
    // await wait(50) // if uncomment this line, the error will be gone
    await queueScheduler.waitUntilReady()
    await queueScheduler.close();
    await connection1.quit();
};
start();
```
I run the program with `DEBUG` mode of `ioredis` to see what's going on and this is the result: 
```
  ioredis:redis status[localhost:6379]: [empty] -> connecting +0ms
  ioredis:redis status[localhost:6379]: [empty] -> connecting +2ms
  ioredis:redis status[127.0.0.1:6379]: connecting -> connect +11ms
  ioredis:redis status[127.0.0.1:6379]: connect -> ready +1ms
  ioredis:redis status[127.0.0.1:6379]: connecting -> connect +1ms
  ioredis:redis status[127.0.0.1:6379]: connect -> ready +1ms
  ioredis:redis write command[127.0.0.1:6379]: 0 -> info([]) +18ms
  ioredis:redis write command[127.0.0.1:6379]: 0 -> evalsha([ '81beff9dde03a16bbfc8557eaca2b17a86216314', '7', 'bull:q1:delayed', 'bull:q1:wait', 'bull:q1:priority', 'bull:q1:paused', 'bull:q1:meta', 'bull:q1:events', 'bull:q1:delay', 'bull:q1:', '1637146066054' ]) +4ms
  ioredis:redis write command[127.0.0.1:6379]: 0 -> quit([]) +3ms
  ioredis:redis write command[127.0.0.1:6379]: 0 -> eval('--[[\n' + '  Updates the delay set, by picking a delayed job that should\n' + '  be processed now.\n' + '\n' + '     Input:\n' + "      KEYS[1] 'delayed'\n" + "      KEYS[2] 'wait'\n" + "      KEYS[3] 'priority'\n" + "      KEYS[4] 'paused'\n" + '      K ... <REDACTED full-length="2079">') +2ms
  ioredis:redis write command[127.0.0.1:6379]: 0 -> quit([]) +2ms
  ioredis:redis status[127.0.0.1:6379]: ready -> close +2ms
  ioredis:connection skip reconnecting since the connection is manually closed. +0ms
  ioredis:redis status[127.0.0.1:6379]: close -> end +1ms
Error: Connection is closed.
    at Function.updateDelaySet (/project/node_modules/bullmq/dist/classes/scripts.js:417:23)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
  ioredis:redis status[127.0.0.1:6379]: ready -> close +2ms
  ioredis:connection skip reconnecting since the connection is manually closed. +4ms
  ioredis:redis status[127.0.0.1:6379]: close -> end +1ms
```
as can be seen the root cause of the error is     `at Function.updateDelaySet (/project/node_modules/bullmq/dist/classes/scripts.js:417:23)`

I don't know whether the cause of the error in our integration tests is the same as snippet above, however I thought it would be a good idea to submit an issue to discuss. My initial guess is that it's related to some delayed commands that get executed while the connection to `Redis` is closed. If I wait after `queueScheduler` initialization(`await wait(50)`) the error will be gone.

environment: 
```
"bullmq": "^1.54.0",
"ioredis": "^4.28.0",
"redis": latest (run using docker)
```

**Comment by roggervalf** [comment]
@shahinghasemi you can try the last version 1.80.5 it should fix the connection error handling
