### ISSUE TITLE
Using Job Id breaks adding jobs to the queue 

### ISSUE THREAD

**Issue by lukepolo** [taskforcesh/bullmq#879]
Trying to use the `jobId` feature, it breaks.  

1.49 : worked example: "gateway-1"

```
  cloud:BullMQQueue <5> unable to add job to queue ReplyError: ERR Error running script (call to f_b46d74d33572ca40d2d8628d089a3616b3dc2193): @user_script:51: @user_script: 51: Lua redis() command arguments must be strings or integers +16s
    at Function.addJob (/opt/qumulex/app/node_modules/bullmq/src/classes/scripts.ts:125:40)
    at Job.addJob (/opt/qumulex/app/node_modules/bullmq/src/classes/job.ts:904:20)
    at Function.create (/opt/qumulex/app/node_modules/bullmq/src/classes/job.ts:180:24)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Queue.add (/opt/qumulex/app/node_modules/bullmq/src/classes/queue.ts:116:19)
    at BullMQQueue.push (webpack-internal:///./node_modules/qx-arch/lib/queue/BullMQQueue.js:87:13) {
  command: {
    name: 'evalsha',
    args: [
      'b46d74d33572ca40d2d8628d089a3616b3dc2193',
      '8',
      'agent-cloud:Version:wait',
      'agent-cloud:Version:paused',
      'agent-cloud:Version:meta',
      'agent-cloud:Version:id',
      'agent-cloud:Version:delayed',
      'agent-cloud:Version:priority',
      'agent-cloud:Version:completed',
      'agent-cloud:Version:events',
      'agent-cloud:Version:delay',
     <Buffer@0x3a72008 97 b4 61 67 65 6e 74 2d 63 6c 6f 75 64 3a 56 65 72 73 69 6f 6e 3a a3 31 32 33 b4 55 70 64 61 74 65 47 61 74 65 77 61 79 56 65 72 73 69 6f 6e cb 42 77 ... 9 more bytes>,
      '{"job":"UpdateGatewayVersion","data":{"online":false,"version":"feature/debugger.1586","wireguardIP":"10.43.152.119"}}',
     <Buffer@0x3a71f90 de 00 07 a8 61 74 74 65 6d 70 74 73 03 a5 64 65 6c 61 79 cd 75 30 a7 62 61 63 6b 6f 66 66 de 00 02 a4 74 79 70 65 ab 65 78 70 6f 6e 65 6e 74 69 61 6c ... 66 more bytes>
    ]
  }
} {
  job: 'UpdateGatewayVersion',
  data: {
    online: false,
    version: 'feature/debugger.1586',
    wireguardIP: '10.43.152.119'
  }
}
```

**Comment by manast** [comment]
Can you provide the full example please?

**Comment by lukepolo** [comment]
sorry it would seem it is random , removing job id thought fixed it but was just a different issue . working on figuring out what's going on as all the code dispatching jobs from 1.49 didn't change.

**Comment by lukepolo** [comment]
future reference for anyone else: removed lock / node modules ,  re-installed node modules and now it seems to be working fine.
