### ISSUE TITLE
problem with redis cluster

### ISSUE THREAD

**Issue by amirAlamian** [taskforcesh/bullmq#906]
Hi I have a Redis cluster with 6 nodes. 3 masters and others are slaves. when I start my application I see this error throws from ioredis

```bash
2021-12-01T12:03:24.226187083Z ReplyError: CROSSSLOT Keys in request don't hash to the same slot
2021-12-01T12:03:24.226224973Z     at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12)
2021-12-01T12:03:24.226230093Z     at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14) {
2021-12-01T12:03:24.226233840Z   command: {
2021-12-01T12:03:24.226237206Z     name: 'evalsha',
2021-12-01T12:03:24.226240963Z     args: [
2021-12-01T12:03:24.226244369Z       '81beff9dde03a16bbfc8557eaca2b17a86216314',
2021-12-01T12:03:24.226247776Z       '7',
2021-12-01T12:03:24.226250942Z       'bull:outlookNotificationQueue:delayed',
2021-12-01T12:03:24.226254298Z       'bull:outlookNotificationQueue:wait',
2021-12-01T12:03:24.226268264Z       'bull:outlookNotificationQueue:priority',
2021-12-01T12:03:24.226272292Z       'bull:outlookNotificationQueue:paused',
2021-12-01T12:03:24.226275848Z       'bull:outlookNotificationQueue:meta',
2021-12-01T12:03:24.226279435Z       'bull:outlookNotificationQueue:events',
2021-12-01T12:03:24.226283162Z       'bull:outlookNotificationQueue:delay',
2021-12-01T12:03:24.226287089Z       'bull:outlookNotificationQueue:',
2021-12-01T12:03:24.226290636Z       '1638360204223'
2021-12-01T12:03:24.226293872Z     ]
2021-12-01T12:03:24.226296867Z   }
2021-12-01T12:03:24.226300554Z }
```

I did some research about this CROSSSLOT error and I found that to avoid getting this error I must use HASH TAG. Bullmq use this Hash Tag feature when you Set prefix key in connection object when you are creating queues or workers. so I did this and again I get this error.
my redis cluster connection is like this

```typescript
    const redisNodes: Redis.ClusterNode[] = [
      {
        port: parseInt(REDIS_PORT),
        host: REDIS_HOST,
      },
    ];
new Redis.Cluster(redisNodes)
```

and I use the queue or worker name as prefix. I create queues using this function

```typescript
  createNewQueue = (name: string defaultJobOptions?: JobsOptions) => {
    const queue = new BullQueue(name, { prefix: name, connection: this.connectionToRedis, defaultJobOptions });
    return queue;
  };

```

Any help?

**Comment by DanielNetzer** [comment]
Hi @amirAlamian we encountered the same issue, it seems that encapsulating queue names with curly brackets solves it.
e.g. {myQueueName}

**Comment by manast** [comment]
This is documented here: https://docs.bullmq.io/bull/patterns/redis-cluster

**Comment by ammirator-administrator** [comment]
@manast 
Documentation is a bit incomplete just by adding prefix to Queue instance is not enough, for workers we have to do the same and it gets resolved

Leaving this here in case someone have the same problem
