### ISSUE TITLE
v1.59.1 client.moveToActive is not a function

### ISSUE THREAD

**Issue by HTM-Bertao** [taskforcesh/bullmq#952]
The lua error is fixed but the client.moveToActivine function error is back
TypeError: client.moveToActive is not a function
    at Function.moveToActive (C:\...\node_modules\bullmq\src\classes\scripts.ts:684:40)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at Worker.moveToActive (C:\...\node_modules\bullmq\src\classes\worker.ts:403:29)TypeError: client.moveToActive is not a function
    at Function.moveToActive (C:\...\node_modules\bullmq\src\classes\scripts.ts:684:40)

**Comment by manast** [comment]
Closing as a duplicate since the original issue has not been resolved yet: https://github.com/taskforcesh/bullmq/issues/946
