### ISSUE TITLE
Failing fast when Redis is down is not working

### ISSUE THREAD

**Issue by pauliusg** [taskforcesh/bullmq#995]
Failing fast when Redis is down is not working as described in https://docs.bullmq.io/patterns/failing-fast-when-redis-is-down  and `await queue.add` is waiting forever when Redis is not reachable.

My code is: 
```
import { Queue } from 'bullmq';
import Redis from 'ioredis';

try {
  const redisClient = new Redis({ enableOfflineQueue: false });
  const queue = new Queue('generic', { connection: redisClient });

  await queue.add('test', { my: 'test' });
  console.log('Added to queue');
} catch (err) {
  console.log('Failed add to queue', err);
}
```

This issue is because `await queue.add` calls https://github.com/taskforcesh/bullmq/blob/92f968198274f97406eaa4324f65dc945ba8fb12/src/classes/scripts.ts#L129

And inside `await (<any>client)` there is a call https://github.com/taskforcesh/bullmq/blob/92f968198274f97406eaa4324f65dc945ba8fb12/src/classes/redis-connection.ts#L138

And until connection is not ready, this promise is not resolved and Redis command  is not even executed. I am seeing errors:
```
Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379
}
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379
}
...
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379
}
...
```

As a workaround temporary I am calling ping command on Redis client
```
import { Queue } from 'bullmq';
import Redis from 'ioredis';

try {
  const redisClient = new Redis({ enableOfflineQueue: false });
  const queue = new Queue('generic', { connection: redisClient });

  await this.redisClient.ping(); // <--------- my workaround
  await queue.add('test', { my: 'test' });
  console.log('Added to queue');
} catch (err) {
  console.log('Failed add to queue', err);
}
```

Having this throws an error immediately on queue add code if Redis is down.

**Comment by manast** [comment]
Yes, this is known actually, I forgot to add a warning about this on the documentation but I have done it now. The limitation is that Redis must be at least online when the queue is initialized. This could be further improved but it is not a trivial fix so it has been postponed.  I will mark this issue as an enhancement.

**Comment by pauliusg** [comment]
@manast understood. I am not a big Redis expert so maybe you could me advise if my workaround is good performance wise?
Maybe I should check `redisClient.status === 'ready'` instead? I really need to fail when Redis is not available because I add tasks from API.

**Comment by manast** [comment]
Did you try with ```await queue.waitUntilReady();``` or is it also failing if the connection has not yet been established?

**Comment by pauliusg** [comment]
@manast as I mentioned earlier waitUntilReady is called inside queue.add method and this exactly is what is not letting to execute Redis command (which would fail if enableOfflineQueue = false) until Redis status is ready. Method code:
```
  static async waitUntilReady(client: RedisClient): Promise<void> {
    if (client.status === 'ready') {
      return;
    }

    if (client.status === 'wait') {
      return client.connect();
    }

    if (client.status === 'end') {
      throw new Error(CONNECTION_CLOSED_ERROR_MSG);
    }

    return new Promise<void>((resolve, reject) => {
      let lastError: Error;
      const errorHandler = (err: Error) => {
        lastError = err;
      };

      const handleReady = () => {
        client.removeListener('end', endHandler);
        client.removeListener('error', errorHandler);
        resolve();
      };

      const endHandler = () => {
        client.removeListener('ready', handleReady);
        client.removeListener('error', errorHandler);
        reject(lastError || new Error(CONNECTION_CLOSED_ERROR_MSG));
      };

      client.once('ready', handleReady);
      client.on('end', endHandler);
      client.once('error', errorHandler);
    });
```

**Comment by manast** [comment]
Ah yes you are right sorry for the confusion. So I guess pinging Redis is the best we can do for now.

**Comment by soumilbaldota** [comment]
Hi @manast, are there any updates on this.
How can I handle errors when instantiating queues.

**Comment by tjhiggins** [comment]
@manast I'm also curious about this. When redis is down my nestjs api will "start", but all requests will hang. Isolated it down to the registerQueue, but unclear why its causing http requests to hang. I already spent too much time on it, but will try to create a minimal repo at some point.

**Comment by manast** [comment]
Looking into this tomorrow...

**Comment by manast** [comment]
I am not sure what is the proper way to do here, because note that if you do this:
```ts
  const redisClient = new Redis({ enableOfflineQueue: false });
  await redisClient.ping();
```
You will get an exception: 
```
358 |             writable = false;
359 |         }
360 |         if (!writable) {
361 |             if (!this.options.enableOfflineQueue) {
362 |                 command.reject(new Error("Stream isn't writeable and enableOfflineQueue options is false"));
                                     ^
error: Stream isn't writeable and enableOfflineQueue options is false
```

So this seems to be a catch 22 moment. If we wait for the connection to be ready we do not fail fast, but if we do not wait it will fail if you try to ping without waiting for the connection to be ready.

**Comment by manast** [comment]
I am leaning towards an option where you can choose if you want to wait for the connection to be ready or not, as otherwise there will always be somebody that is not happy with the provided fixed behaviour.

**Comment by tjhiggins** [comment]
> I am leaning towards an option where you can choose if you want to wait for the connection to be ready or not, as otherwise there will always be somebody that is not happy with the provided fixed behaviour.

That makes sense to me. I'd still want the offline queue for a small redis blip, but I don't want my API service to not start if redis is down. Basically I don't want my API to be dependent on redis.

**Comment by manast** [comment]
I think we can close this now as a solution has been provided.
